### ISSUE TITLE
Tags in profiles don't override previous profiles

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#1056]
### Steps to reproduce

```
wwctl profile set --tagadd slurmctldhosts=sched000,sched001 p1
wwctl profile set --tagadd slurmctldhosts=test-sched000 p2
wwctl node set --profile p1,p2 n1
wwctl node list -a n1 | grep slurmctldhosts
```

### Error message

```
wwctl node list -a n1 | grep slurmctldhosts
  n1    Tags[slurmctldhosts]          p1         sched000,sched001 
```

Expected output is for the tag to have the value `test-sched000`.

### Information on your system

```
$ wwctl version
wwctl version:	 4.5.x-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.x-1"

$ rpm -q warewulf
warewulf-4.5.x-1.git_bd54993e.el9.aarch64
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

**Comment by anderbubble** [comment]
@mslacken and @griznog I think the desired behavior described here is what we'd want to happen; but I'm afraid I've missed something. What do you think?

**Comment by griznog** [comment]
The behavior historically has been all over the place. At some point we should define profile + node config merging rules and document them, then the algorithm should implement those rules. There are a bunch of different ways to handle this, but not having a documented "this is how it is supposed to work" leaves a lot of trial and error figuring out what it does new after each change.

**Comment by anderbubble** [comment]
@griznog agreed. I want to get this documented, among virtually everything else, as part of this release.

For this case, this ended up being fixed by an already-pending PR.
