### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by mslacken** [hpcng/warewulf#119]
I have tried to add boot an aarch64 node form x86 host running warewulf v4. For this I added an aarch64 container as an docker image. I also added the kernel from this container (see #120). After a restart of tftp did only boot to ipxe and showed following error

```
iPXE 1.21.1+ (g56f7d) -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP iSCSI TFTP AoE EFI Menu

net0: 52:54:00:0f:75:a0 using SNP on SNP-0000:01:00.0 (Ethernet) [open]
  [Link:up, TX:0 TXE:1 RX:0 RXE:0]
  [TXE: 1 x "Network unreachable (http://ipxe.org/28086090)"]
Configuring (net0 52:54:00:0f:75:a0)...... ok
net0: 192.168.100.103/255.255.255.0
net0: fe80::5054:ff:fe0f:75a0/64
Next server: 192.168.100.250
Filename: http://192.168.100.250:9873/ipxe/52-54-00-0f-75-a0
http://192.168.100.250:9873/ipxe/52-54-00-0f-75-a0... ok
[Security] 3rd party image[0] can be loaded after EndOfDxe: .
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 43A5AEC40
Unloading driver at 0x00000000000
52-54-00-0f-75-a0 : 784 bytes [script]

================================================================================
Warewulf v4 now booting: arm01

Container: leap-15.3-arm-hpc:latest
Kernel: 5.3.18-59.19-default.gz
KernelArgs: crashkernel=no

http://192.168.100.250:9873/kernel/52-54-00-0f-75-a0... ok
[Security] 3rd party image[0] can be loaded after EndOfDxe: .
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 43A5AE1C0
Unloading driver at 0x00000000000
Could not select: Exec format error (http://ipxe.org/2e008081)

There was an error, rebooting in 15s...

```

Even this error is fixed, I would need a executable of `wwclient` for arch64. I can achieve this by creating a `default-aarch64` system profile and adding a aarch54 executable to this profile. Is this the best practice way to crossboot in warewulf, or should there be an architectur flag added?

**Comment by mslacken** [comment]
I also see following messages in `/var/log/wareulfd.log`
```
[LOG]      IPXEREQ:   /ipxe/52-54-00-0f-75-a0
[LOG]      IPXE:            arm01: /ipxe/52-54-00-0f-75-a0
[LOG]      SEND:            arm01: /etc/warewulf/ipxe/default.ipxe
[LOG]      REQ:             arm01: /kernel/52-54-00-0f-75-a0
[LOG]      SEND:            arm01: /var/lib/warewulf/provision/kernel/5.3.18-59.19-default.gz/vmlinuz
[LOG]      UNKNOWN: 192.168.100.101: /overlay-runtime
[LOG]      UNKNOWN: 192.168.100.101: /overlay-runtime
[LOG]      UNKNOWN: 192.168.100.101: /overlay-runtime
[LOG]      UNKNOWN: 192.168.100.101: /overlay-runtime
[LOG]      UNKNOWN: 192.168.100.101: /overlay-runtime
[LOG]      UNKNOWN: 192.168.100.101: /overlay-runtime
[LOG]      UNKNOWN: 192.168.100.101: /overlay-runtime
[LOG]      UNKNOWN: 192.168.100.101: /overlay-runtime
[LOG]      UNKNOWN: 192.168.100.101: /overlay-runtime
[LOG]      UNKNOWN: 192.168.100.101: /overlay-runtime
```

**Comment by bensallen** [comment]
The exec format error in iPXE is likely one of two things:

1. Linux doesn't have a built-in decompressor in the kernel for aarch64, nor does iPXE (or at last didn't until recently https://github.com/ipxe/ipxe/commit/866fa1ce7 it appears). Thus if /var/lib/warewulf/provision/kernel/5.3.18-59.19-default.gz/vmlinuz is gzip compressed, it needs to be decompressed.
2. Since this looks like a Suse 15.3 kernel, you actually need to use /boot/Image-5.3.18-59.19-default, which is the Portable Executable (PE) formatted version of the kernel. EL based distros gzip compress this format of the kernel and name it vmlinuz (which requires 1 above). You can validate the format of the kernel as correct with `file` reporting the file somewhat erroneously as "MS-DOS executable", or more thoroughly via `hexdump -C ... | head`:

```
00000000  4d 5a 00 91 ff 3f 3f 14  00 00 08 00 00 00 00 00  |MZ...??.........|
00000010  00 c0 15 02 00 00 00 00  0a 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  41 52 4d 64 40 00 00 00  |........ARMd@...|
00000040  50 45 00 00 64 aa 02 00  00 00 00 00 00 00 00 00  |PE..d...........|
```

**Comment by gmkurtzer** [comment]
please check PR #137. I think that implements the appropriate fixes including gzip'ing the ARM kernel with or without the `.gz` suffix.

**Comment by bensallen** [comment]
@gmkurtzer for Suse ARM support I think you'll need to update https://github.com/hpcng/warewulf/blob/main/internal/pkg/kernel/kernel.go#L75 and perhaps https://github.com/hpcng/warewulf/blob/main/internal/pkg/kernel/kernel.go#L32 as well. Adding support for detecting kernel filenames such as /boot/Image-5.3.18-59.19-default.

#137 looks good to me for automatically decompressing kernels.

**Comment by mslacken** [comment]
We also have now arbitrary names for kernels via #139

**Comment by gmkurtzer** [comment]
The PR #139 has been merged which addresses @mslacken's issue as well as the pointers that @bensallen referred to.

Thanks everyone!
