### ISSUE TITLE
Canary testing for images, overlays, and kernel

### ISSUE THREAD

**Issue by gmkurtzer** [hpcng/warewulf#130]
Simplify the process of A/B testing with updates and testing (e.g. copying container images (not possible right now).

How do you keep jobs from landing on testing environments? (possibly use a profile with a different "clustername" which will be interpreted as a domain suffix)

**Comment by anderbubble** [comment]
@gmkurtzer since I don't recall anyone talking about this recently, I'm removing this from the 4.3.0 milestone and not moving it to 4.4.0; but of course add it there if you think it should be kept in for 4.4.0.

**Comment by mslacken** [comment]
The question here is, doe this need code in warewulf or is it enough to have separate overlays?

**Comment by anderbubble** [comment]
I think we at least need to make it possible to clone an existing container to a new one. (Or has that already been added?)
