### ISSUE TITLE
missing system overlay image when specifying hwaddr

### ISSUE THREAD

**Issue by syserr** [hpcng/warewulf#146]
## Describe Bug
In master and release 4.1.0, when nodes are added with --hwaddr specified, then the system overlay image is not created.  The --hwaddr would be used during a bulk allocation of nodes in order with known MAC addresses.

## To Reproduce
```wwctl node add opa1.cluster --netdev eth0 -I 192.168.1.150 --hwaddr 50:xx:xx:xx:xx:xx```

## No Reproduce
```wwctl node add opa1.cluster --netdev eth0 -I 192.168.1.150 --discoverable```

## Details

Nodes created with `--hwaddr` never get a chance to have system images created for them.  The first hint at this is after ipxe the booting system halts with a kernel panic.

Investigating /var/log/warwulfd.log:
```ERROR: open /var/warewulf/provision/overlays/system/opa1.cluster.img: no such file or directory```

If a node is created with `--discoverable` and not `--hwaddr`, then the system image is created during ipxe and the node boots fine.

In `/internal/pkg/warewulfd/ipxe.go` there is conditional logic, different actions based on node configuration.  If a node has a `hwaddr` it ends up being considered "configured." (as if it has already been discovered and images built) 

I was able to get better behavior by copying
```
		_ = overlay.BuildSystemOverlay([]node.NodeInfo{nodeobj})
		_ = overlay.BuildRuntimeOverlay([]node.NodeInfo{nodeobj})
```
currently already at line 84-85 and also putting it in the bottom else condition around line 121.

This "fix" creates them brute-force every time the system boots though.  Likely, the best thing to do is create the images if they don't already exist.

**Comment by gmkurtzer** [comment]
This is a good catch and something that is indeed confusing. The thought process around it was that if a node is discoverable, it must generate overlays when the node boot is attempted. But, if someone configures it by hand, it shouldn't do it by default.

In a recent community meeting, this was brought up, and it was determined that we should always create/cache the overlays if they aren't already created. We could even do a time stamp comparison to see if any configs were updated since the overlay was generated, and even generate proactively.

**Comment by syserr** [comment]
That would be great!  Something confusing, I thought maybe the `wwctl overlay build system system` may brute-force create these images.  It doesn't seem to.  Does it just ensure the inheritance of the overlays to the node level variables?

If `wwctl overlay build system system` is not intended to (re-)build images, then I think a new command to do this would be a great addition.

**Comment by gmkurtzer** [comment]
@syserr, please check out #157. The Warewulfd will not rebuild overlays as needed on demand. Granted, for large systems, it is always going to be best to statically generate/build them using `wwctl overlay build ...`.

Hoe that helps and this will be included in the next major release (which should be very soon now).
