### ISSUE TITLE
RFE: Container specific configuration

### ISSUE THREAD

**Issue by gmkurtzer** [hpcng/warewulf#155]
A configuration file inside the container root that has information like what files/directories to exclude (and maybe other things looking forward).

**Comment by jcsiadal** [comment]
I was just about to add this as a feature request. I need to exclude some directories from the compressed tarball, and I'd like to have some directories replaced by links. Unlike the old hybridize, I'd define the link targets individually.

I don't want to permanently modify the chroot, as that can impact RPM/APT updates.

I was thinking that an optional YAML file in the same directory as rootfs under chroots would make the most sense.
