### ISSUE TITLE
'kernel import --container' typically won't find a kernel

### ISSUE THREAD

**Issue by rhenwood-arm** [hpcng/warewulf#156]
After installing a kernel in RockyLinux container `dnf install kernel-modules-extra` the kernel isn't in `/boot`. It is available in `/lib/modules/4.18.0-305.19.1.el8_4.aarch64/vmlinuz`. 

After installing a kernel in Alpine: `apk add linux-lts`, `/boot` is populated, but the kernel has the name: `vmlinuz-lts`.

I looks like the assumption that the kernel will be in `/boot` and is called `vmlinuz-$kernelVersion` is made here:
https://github.com/hpcng/warewulf/blob/a71c060b15a7f520d48d82b23dbe110d07840658/internal/pkg/kernel/kernel.go#L75

My first thought is that it might be good provide a way to override this assumption with arbitrary kernel location, in the case of a kernel import from a kernel?

**Comment by gmkurtzer** [comment]
Did you also install `kernel-core` package? That is what installs the file in `/boot/vmlinuz*`.

**Comment by rhenwood-arm** [comment]
yep: `kernel-modules-extra` pulls in `kernel-modules`, `kernel-core`, and `linux-firmware`.

**Comment by gmkurtzer** [comment]
@rhenwood-arm That is very interesting... hrmm... What is the full path to the kernel and the modules directory for that kernel?

**Comment by rhenwood-arm** [comment]
In the case of Rocky: `/lib/modules/4.18.0-305.19.1.el8_4.aarch64/vmlinuz`
and for Alpine: `/lib/modules/5.10.61-0-lts/`

**Comment by gmkurtzer** [comment]
You mentioned there was a vmlinuz-lts named kernel?

**Comment by rhenwood-arm** [comment]
yes: for the Alpine container example, installing `apk add linux-lts` gives me:

path to kernel: `/boot/vmlinuz-lts`
path to modules: `/lib/modules/5.10.61-0-lts/`

for Rocky:

path to kernel: `/lib/modules/4.18.0-305.19.1.el8_4.aarch64/vmlinuz`
path to modules: `/lib/modules/4.18.0-305.19.1.el8_4.aarch64/`

**Comment by gmkurtzer** [comment]
ok, I wasn't expecting the path to kernel on rocky side to be there, but that's an easy enough thing to fail over to look for.

Regarding the Alpine location, that is interesting indeed. Does it also exist at `/lib/modules/$(uname -r)/vmlinuz`? If so, that would help a lot.

**Comment by gmkurtzer** [comment]
@rhenwood-arm Will you check out the above patch to see if that helps?

**Comment by rhenwood-arm** [comment]
Alpine dosen't appear to have a `vmlinuz*` anywhere in `/lib/modules*`. 

Thanks for the patch Greg - I will test it on Monday. I like the idea of testing a number of likely locations and name combinations. I think the rules you've created cover most things - but I think it would be great if I could also specify the kernel path and modules directly.

Also: I really appreciate your attention to this use case. In my opinion this is a hugely valuable feature for Warewulf!

**Comment by gmkurtzer** [comment]
Yeah, I think you are right... It should probably be a flag to the `wwctl kernel import ` command such that we can select any binary image to include.

My pleasure and I completely concur!

**Comment by gmkurtzer** [comment]
Didn't @mslacken fix this with the `-D` flag to the kernel import?

**Comment by mslacken** [comment]
> Didn't @mslacken fix this with the `-D` flag to the kernel import?

Not intentionally but more by accident :-). But I think this issue can be closed by now, as the whole kernel management gets changed anyway.

**Comment by mslacken** [comment]
Fixed with #379
