### ISSUE TITLE
Unable to load modules for Ubuntu focal node

### ISSUE THREAD

**Issue by jgans** [hpcng/warewulf#166]
Hello, I am attempting to use Warewulf v4 to build a cluster of Ubuntu "focal" nodes. The kernel, container, kmods and system images all appear to be downloaded by iPXE. However, after the kernel has booted, there is no network connectivity or USB keyboard support. Tcpdump on the control server shows no traffic on the private network that is shared with the node. Looking at the boot information for the node (by removing the "quiet" flag from the kernel arguments) shows that there is no PCI or USB device discovery (hence the lack of network and keyboard support?). It appears that the modules, downloaded as "kmod" in the iPXE script, are not being loaded when the kernel is booted. Any advice to enable module loading would be most welcome!

**Comment by jgans** [comment]
Thanks -- I copied all of the kernel modules from the host system to the container. After booting a cluster node, the USB keyboard now works, but still no network connection.

**Comment by gmkurtzer** [comment]
So the `kmods` layer that is provisioned should already include ALL of the kernel modules for that particular kernel. Can you test this by removing the kernel modules you installed into the container, rebooting, and then checking out `ls /lib/modules/$(name -r)`? You should see your entire kernel module tree there. Also, do a `lsmod` to see what kernel modules are loaded.

Is the network not connecting due to lack of kernel modules or is it not configured?

Thanks!

**Comment by gmkurtzer** [comment]
@jgans Thank you for your patience and help as we figure this out.

Can you check two things for me:

1. I don't see the output of the contents of the kmods.img. I would like to understand if the kernel modules are just not getting properly added to that archive. If you aren't familiar with how to break that open, you can just show me the output of `du -sh /var/warewulf/provision/kernel/*/kmods.img`.
2. On the host, you show the kernel modules existing in `/usr/lib/modules/`. Is `/lib` a symlink to `/usr/lib` by chance?

Thanks!

**Comment by mslacken** [comment]
@jgans How did you import the kernel to warewulf. When you did this via `wwctl import kernel -C $CONTAINERNAME ` or `wwctl import kernel -r $ROOTPATH`, the kmod image is build in the wrong way and thus the modules can't be loaded. A fix is underway in #172
