### ISSUE TITLE
wwctl not executable by users if nodes.conf is secure

### ISSUE THREAD

**Issue by jcsiadal** [hpcng/warewulf#175]
The issue here is that the 0640 permission change to nodes.conf prevents users from executing wwctl. Regular users use wwsh in Warewulf 3 to get cluster info and node status, but there would be no comparable capability in WW4. I don't think that's what we want, but we do need to keep passwords secure.

I recommend one of two options:
[Below, I use the terms key and value specifically for YAML key:value pairs]
1) Create a second YAML file readable only by root for storing protected data. Same structure, but only keys that need to be secure (it will be a sparse file). List secure keys in a go map; when reading or writing, if the key is in the map, write to the secure file; otherwise, write to the regular file. When loading all keys, overlay the secure file over the regular file.

2) Implement an import flag, similar to PyYAML. If a value begins with "!import:", read contents of the file as the value for that key. This would require one file per secured key. Don't change current nodes.conf writes, but provide a wwctl option to write values to a file and set the import flag.

(To be fair, there is option 3: create non-sparse overlays like Kustomize uses, but that's more than we need).

If the ultimate decision is that wwctl is only usable by root, it needs to move into /usr/sbin.

**Comment by jcsiadal** [comment]
There is an option 3: I perused the viper package that cobra uses. It can selectively read/write key-encrypted values to YAML. My opinion is that this would be the optimal solution.

**Comment by mslacken** [comment]
We have no concept for unprivileged users to touch `nodes.conf`, so this one is invalid

**Comment by anderbubble** [comment]
@mslacken this issue is to _raise_ the question of unprivileged users touching `nodes.conf`.

Flagging for future discussion.
