### ISSUE TITLE
Extensions for handling NFS and fstab files

### ISSUE THREAD

**Issue by robgjansen** [hpcng/warewulf#183]
I've noticed some issues with NFS handling:

- [ ] `wwctl configure nfs` does not honor the `enabled` option (it always overwrites /etc/exports)
- [ ] Can't specify options for nfs mounts
- [ ] Can't add exports on controller without also mounting them on nodes
- [ ] Can't easily add node-specific mounts (e.g. local hdds or ssds) to fstab

More rationale below.

---

Currently, we specify NFS exports in the `warewulf.conf` file like this:

```
exports:
  - /home
  - /var/warewulf
```

Because wwctl manages the `/etc/exports` file, it is difficult to add custom options when mounting these on the nodes, and it is difficult to export the shares without mounting them statically on the nodes (e.g., I want to use autofs instead of static mount for some of the shares).

---

The `/etc/fstab` file is managed by `wwctl configure nfs` but it doesn't offer a convenient way to specify local node-specific mounts. I wonder if we might want to write a `/etc/fstab.ww` template instead, and then expose a way for each node to add a mount string to an array that will then get added to the end of `/etc/fstab.ww`.

**Comment by mslacken** [comment]
solved in #240 , please reopen if not all was implemented
