### ISSUE TITLE
Don't overwrite existing template files in `wwctl configure`

### ISSUE THREAD

**Issue by robgjansen** [hpcng/warewulf#185]
Modifications to some of the default `.ww` template files (e.g., /etc/hosts) are blown away and overwritten by the defaults when running `wwctl configure ...`. It would be helpful if the default behavior was to NOT overwrite existing files unless a `--force` option or similar were specified by the user.

**Comment by mslacken** [comment]
With #304 the whole management of host overlays changed and this should have been addressed
