### ISSUE TITLE
runtime overlay client identification is based on IP addr only

### ISSUE THREAD

**Issue by kivel** [hpcng/warewulf#192]
#### change client identifying entity
The client identification for runtime overlays is based on the IPv4 address only.
This will fail for IPv6 clients, and for clients configured w/o static IP addresses.

https://github.com/hpcng/warewulf/blob/4272e13fa3f17394bed8fa8dfb05ecd5196837b1/internal/pkg/warewulfd/runtime.go#L30

**suggestion:**
change client identification key to a unique entity, i.e. MAC. The MAC is needed anyway as the ipxe processes is based on it.
However, since the whole idea behind this is security, the new identification method should be carefully evaluated in this regard.

**Comment by mslacken** [comment]
Was closed with #196
