### ISSUE TITLE
`wwctl container exec` doesn't detect file owner/permission change when exit and decide not to build VNFS

### ISSUE THREAD

**Issue by panda1100** [hpcng/warewulf#193]
`wwctl container exec` doesn't detect file owner/permission change when exit and decide not to build VNFS.

https://github.com/hpcng/warewulf/blob/4272e13fa3f17394bed8fa8dfb05ecd5196837b1/internal/pkg/util/util.go#L22-L41

**Comment by mslacken** [comment]
Was fixed
