### ISSUE TITLE
Unable to uniquely reference node in wwctl

### ISSUE THREAD

**Issue by robgjansen** [hpcng/warewulf#203]
I have nodes named `node1` and `node10`. Whenever I try to set an attribute on `node1` (e.g., `wwctl node set -y ipmiaddr 10.0.0.1 node1`), wwctl also applies it to `node10`. I am unable to find a way to target `node1` but not `node10`.

**Comment by mslacken** [comment]
There is no way to target `node1` right now, but I fixed this in #205. 
Traditionally node names are zero padded, node would have `node01` what avoids this problem.
Thanks for bringing this up.

**Comment by mslacken** [comment]
was closed #205
