### ISSUE TITLE
RFE: Extend IPMI Configuration To Include HW Address

### ISSUE THREAD

**Issue by elguero** [hpcng/warewulf#206]
If a BMC is setup to get an IP by way of DHCP and Warewulf is going to manage that, we need to have the ability to set the HW address in the configuration for the device on a node.

**Comment by mslacken** [comment]
Starting with version 4..3.0  you can have arbitrary tags, also for the ipmi device.  The command for this is:
```
wwctl node set node01 --ipmitagadd mac=11:22:33:44:55:66
```
As there is also a need for a handcrafted `dhpcd,conf.ww` template, it is no sensible to have the ipmi mac address stored for non standard configurations.
