### ISSUE TITLE
RFE: Convert HW Address Values From CLI To Lower Case

### ISSUE THREAD

**Issue by elguero** [hpcng/warewulf#213]
We need to convert any HW addresses being input by the user or read from YAML (direct edit) to lower case.  It would be good to do a sanity check when reading in the data structure.

**Comment by jcsiadal** [comment]
We should probably use current IEEE standards when writing new EUI-48 content. The spec supports either upper or lower case, but specifies six 2-byte fields separated by dashes, or one 12-byte field. IEEE docs seem to use only uppercase hex fields and dashes.

For reading from the file or command line, we should support any case, colons, dashes, or no separator.

**Comment by elguero** [comment]
This issue should be resolved by https://github.com/hpcng/warewulf/pull/384.
