### ISSUE TITLE
wwctl container delete does not delete image

### ISSUE THREAD

**Issue by mslacken** [hpcng/warewulf#214]
The `wwctl container delete ` does not delete its related img.gz file under `/var/warewulf/provision/container/`

**Comment by jcsiadal** [comment]
Can we fix before 4.4? This seems like a bug.

**Comment by MatthewHink** [comment]
Maybe `--delete-image` should be a command line option? We should discuss tomorrow.

**Comment by jcsiadal** [comment]
I think users' interpretations of "delete" is that all things related to the named container should be deleted. If there is a reason to keep the image, then an option like "--save-image" would make sense. Yes, let's review tomorrow.

**Comment by MatthewHink** [comment]
Makes sense to me.

**Comment by MatthewHink** [comment]
Going to recant. This is an on disk leak.
