### ISSUE TITLE
Relocate Warewulf server file store to meet FHS

### ISSUE THREAD

**Issue by jcsiadal** [hpcng/warewulf#219]
I know we had a pull request for this earlier, but I didn't see any open issues.

Move /var/warewulf to either /srv/warewulf or /var/lib/warewulf by default, and add an option to change the location.

Current FHS specifies software should not write into /var directly, unless general approval is obtained on the FHS mailing list. For exported server packages, I see that Red Hat typically uses /var/lib and SUSE and Ubuntu use /srv. My preference is /srv.

The default location should be configurable in the Makefile, with override supported in /etc/warewulf/warewulf.conf.

**Comment by mslacken** [comment]
The pr was #87 which I closed more or less by accident. With that PR it would have been able to configure the location via `/etc/warewulf/warewulf.conf`.I think now, it might be more useful to configure this locations at compile time and add their actual values to the `wwclt version` command.

**Comment by jcsiadal** [comment]
I'm going to setup the Makefile to set the default install directories for warewulf and tftp, and then inject those variables into the go build. Users can override the default values when launching make.

The runtime value can also be set in warewulf.conf. This will let us distribute an RPM/DEB, but permit admins change directories after install.

We could have make detect the distro and choose defaults accordingly, but I don't believe the benefit is worth the effort.

**Comment by mslacken** [comment]
@jcsiadal in order to get rid of the warning/errors regarding missing `warewulf.conf` and `nodes.conf` from the man and bash_completion generation, the associated variables are set in the `Makefile`.

I think we do not need to explicitly detect the distros, as the paths can be configured via rpmmacros.

**Comment by jcsiadal** [comment]
Submitted PR #229

**Comment by jcsiadal** [comment]
Merged with #229.

**Comment by jcsiadal** [comment]
Broken again after updates. Everything needs to go under a runtime configurable datastore, but especially the containers and chroots.

**Comment by jcsiadal** [comment]
This is fixed in 4.3rc1.
