### ISSUE TITLE
`wwctl` operations for `build` have none atomic products

### ISSUE THREAD

**Issue by kivel** [hpcng/warewulf#220]
I think there is a potential issue with `wwctl kernel|container build` when re-importing a kernel or re-building a container which is in use. The command might fail and leave the *.img in a broken state.
Also, the files might be accessed during the build phase.

https://github.com/hpcng/warewulf/blob/503480809b2a33a28d1488fa40d5226c6aa38f2e/internal/pkg/kernel/kernel.go#L181

https://github.com/hpcng/warewulf/blob/503480809b2a33a28d1488fa40d5226c6aa38f2e/internal/pkg/container/build.go#L53

**Comment by mslacken** [comment]
The image build process chnaged in 4.3.0, as this is not just a pipe any more. So this should be closed.
