### ISSUE TITLE
Does ARM support `imgextract` in iPXE?

### ISSUE THREAD

**Issue by gmkurtzer** [hpcng/warewulf#236]
We need to determine if `imgextract` is supported properly on ARM iPXE which I seem to recall doesn't properly support zlib compression.

If this works properly on ARM, then we should make `imgextract` the default iPXE method for retrieval of the initrd layers.

Re: #235

**Comment by rhenwood-arm** [comment]
Today, I know that AArch64 iPXE is missing the ability to _boot_ a gz image: https://github.com/ipxe/ipxe/blob/bfca3db41e9af78e56e7a9b7f30121df83b6af0a/src/arch/x86/image/bzimage.c#L523

I've had a quick browse of the iPXE source and it appears that there may be support for imgextract. Can you suggest a test I can perform to gain confidence with iPXE AArch64?

**Comment by kcdodd** [comment]
I ran into `imgextract` not being supported in the amd64 computer I started using to test as the client/node. It seems (looking at the source) both the `imgextract` command and gzip itself could be disabled in any build of iPXE. In #423, its treated as a "duck test", starting by trying to use `imgextract`, and if it fails try again with the `initrd` command.
