### ISSUE TITLE
erratic dhcp configuration

### ISSUE THREAD

**Issue by mslacken** [hpcng/warewulf#244]
The field
```
  template: default
```
has an erratic behavior. With the actual configuration `wwctl configure` would search for the file `defaultdhcpd.conf` and not the actual installed `default-dhcpd.conf``.  I would suggest not to add the suffix `dhcpd.conf` but use the template value as relative file name.

The relevant code is:
https://github.com/hpcng/warewulf/blob/29c628cb79b11985fc4ff6b5c59ccca4694bcdd2/internal/app/wwctl/configure/dhcp/main.go#L87-L95

**Comment by MatthewHink** [comment]
I think this was fixed here: https://github.com/hpcng/warewulf/pull/256
