### ISSUE TITLE
wwctl can't set netdev

### ISSUE THREAD

**Issue by mslacken** [hpcng/warewulf#246]
` wwctl node set node01 --netdev=eth0 --netname=default` will no set the netdev of the node.
As workaround `/etc/warewulf/nodes.conf` can be modified directly.

**Comment by MatthewHink** [comment]
This is a bit confusing. netdev is an alias for netname
```wwctl node set node01 --netdevice=eth0 --netname=default``` will set the device.

```wwctl node set node01 --netname=newNetName``` is adding new entries for device, hwaddr, ipaddr, netmask, gateway, type, onboot, and default. It's not clear to me if that is intended behavior.

**Comment by mslacken** [comment]
> This is a bit confusing. netdev is an alias for netname `wwctl node set node01 --netdevice=eth0 --netname=default` will set the device.

That is the point, `netdev` *must not*  be an alias to `netname`. For a new node, a `netdev` and a `netname` must be set. Before the refactoring of the `netdev` for `netname==default` was always `eth0`.

**Comment by mslacken** [comment]
was fixed
