### ISSUE TITLE
RFE: Separate functional code from interface

### ISSUE THREAD

**Issue by jcsiadal** [hpcng/warewulf#249]
Update app/wwctl and move functional code to the /pkg modules. wwctl should be limited to Cobra functions. This will enable other commands to replicate wwctl capabilities without including that user interface.

There is no user impact -- everything should look and operate the same from a wwctl user perspective.

Please assign to me. I'm going to submit these as a PR for each subcommand to limit later difficulties with rebasing.

**Comment by mslacken** [comment]
Most of this stuff happened with the new API.
Still there are some parts which can not be moved out of `app/wwctl` e.g. the `container exec` part, which is tightly coupled to the used terminal.
