### ISSUE TITLE
Default Warewulf 4 installation is not LSB-compliant

### ISSUE THREAD

**Issue by jcsiadal** [hpcng/warewulf#255]
Assuming a new user to Warewulf using default parameters, the resulting cluster should be LSB-compliant. This will require relocating the default installation paths.

Instead of LOCALSTATEDIR, we should use LOCALSTATEDIR/lib (standard install path for Red Hat and SUSE) or SHAREDSTATEDIR (this is what Red Hat is migrating to).

We also need to eliminate the /usr/local/var and /usr/local/srv that are created in current main branch.

**Comment by mslacken** [comment]
should be fixed with #334
