### ISSUE TITLE
kernel: Improve importing kernel modules

### ISSUE THREAD

**Issue by elguero** [hpcng/warewulf#281]
Version: 4.2.0-2
OS: CentOS 7
Drivers: MLNX_OFED_LINUX-4.9-4.1.7.0-rhel7.9-x86_64

When installing kmods, they might be compiled against a specific kernel.  On minor point kernel updates, rather than rebuild the kernels a symlink is used.

`wwctl kernel import` copies in the symlink for the kernel being imported but does not copy the actual file.  When a node is provisioned with a different kernel, the symlink to the kmod is pointing to a non-existent file on the node.

**Comment by gmkurtzer** [comment]
This has been merged and fixed. Thanks @elguero !
