### ISSUE TITLE
Adding a node doesn't add it's hostname in the controller node

### ISSUE THREAD

**Issue by richang2009** [hpcng/warewulf#289]
Need to have an automatic mechanism to add the hostname of the newly added nodes to the /etc/hosts file of the controller node.

**Comment by gmkurtzer** [comment]
At present, `/etc/hosts` isn't updated automatically, but it is updated via `wwctl configure hosts`. Just to be clear, are you thinking it should be triggered by every node update, or is `wwctl configure hosts` good enough?

Thanks!

**Comment by mslacken** [comment]
With the host overlays `/etc/hosts` is updated with a `wwctl overlay build -H`.
