### ISSUE TITLE
RFE: Overlay Enhancements: Allow arbitrary scripts in overlay processing. 

### ISSUE THREAD

**Issue by griznog** [hpcng/warewulf#310]
Following up on #309 , with the overlay content moved into a `rootfs` subdirectory, add a directory at, for instance,

```
warewulf/overlays/OVERLAYNAME/scripts/[pre|post]
```
Which if it exists would have any scripts in that location ran with a set list of arguments, given a script:

```
warewulf/overlays/OVERLAYNAME/scripts/[pre|post]/my_script.sh
```

The script would be called with (pseudocode)

```
warewulf/overlays/OVERLAYNAME/scripts/[pre|post]/my_script.sh NODENAME TMP_IMAGE_PATH
```
stdout/stderr of the script(s) should be logged, exit code > 0 considered a fatal error in building the overlay image.

The `pre` and `post` directories woudl be called before and after the normal ww template processing respectively.

This would allow the use of arbitrary scripts while building the overlays, providing the ability to use more complex logic than a template can support and in any language meeting local preference.

**Comment by mslacken** [comment]
Nice idea, but I would suggest to have the scripts as templates, so this would be something like
```
warewulf/overlays/OVERLAYNAME/scripts/[pre|post]/my_script.sh.ww
```
so that we do not have to preselect which variables go into script, but can include them via templates.

**Comment by griznog** [comment]
I'm assuming the overlay build process would work like so with optionally templated scripts (pardon the BASH-ish pseudocode):

```
for file in ${OVERLAY}/pre/*; do
  if is_template $file; then
    process_template $file > tmp.script
    exec tmp.script NODENAME TMP_IMAGE_PATH
  else
    exec $file NODENAME TMP_IMAGE_PATH
  fi
done
normal_overlay_process # whatever happens now to get files to the temp directory
for file in ${OVERLAY}/post/*; do
  if is_template $file; then
    process_template $file > tmp.script
    exec tmp.script NODENAME TMP_IMAGE_PATH
  else
    exec $file NODENAME TMP_IMAGE_PATH
  fi
done
make_cpio_image # whatever happens to convert temp directory to the deployed overlay image
```

**Comment by griznog** [comment]
Also in my thought experiment for how I'd use this I always assume that the script in question would process `/etc/warewulf/nodes.conf` itself and only need to know which NODENAME it was being ran for and where the temp overlay image was being assembled to figure out everything it needed to know.

**Comment by Prepultrue** [comment]
Having the script process `nodes.conf` sounds overly onerous on the script.
For example, obtaining a key that's successively overwritten by a handful of profiles on a node, would be a bunch of boilerplate to any script that might want to access items not directly specified on the node.

Passing the script a JSON file which contains what is already available to templates would allow scripts to access config entries as evaluated by warewulf with relative ease, or template the scripts themselves as @mslacken suggested.

**Comment by gmkurtzer** [comment]
Can you share some use-cases that you are trying to fix/create with this RFE?

**Comment by griznog** [comment]
The canonical one is complex networking setups. A template can't produce multiple files, so given a heterogeneous environment with multi-homed nodes, VLANs, bridges, static routes, BIOS device names,..., using templates becomes effectively impossible for configuring networking. The problem simplifies tremendously in a script which can read the nodes config and generate the resulting network config. I'm doing this now post-boot via scripts in the container but would like to move that into a container which configures networking and (per the associated RFEs to this one) be shared with the community in a warewulf friendly way. 

There's a philosophical element to this, should Warewulf be a configuration tool/engine? My personal stance on that is why not? Overlays potentially make this at least as manageable as any of the over-hyped tools out there in the world and in the end config management isn't really a hard problem to solve in a stateless node paradigm where basically and literally everything in the node life cycle is idempotent.

**Comment by griznog** [comment]
Specific to the networking use case, I have a branch in my local warewulf fork where I'm teaching myself Go by adding every known setting that is used by RHEL network-scripts and NetworkManager to be first class citizens in the netdev data structure. Not progressing as fast as I'd like, the real world not seeming to care that I'd rather be doing this but eventually I hope to have it merge-able. That'd be the basis for the use case I'm describing here, the node config would have everything it needed to produce arbitrarily complex networking configs by passing the node config to a relatively simple script.

**Comment by mslacken** [comment]
Closing this issue, as we can have multiple files #337 and network keys #351
