### ISSUE TITLE
Import kernel with non-standard naming convention

### ISSUE THREAD

**Issue by TerranWorks** [hpcng/warewulf#314]
We're experimenting with setting up an arch linux cluster and are unable to import the kernel image because on arch the image is called vmlinuz-linux but the modules are stored in /lib/modules/$(uname -r). I know arch isn't supported well but I was curious if anyone has a work around or if I need to edit the warewulf source code.

Also, if anyone knows how to set a different dhcpd.conf directory in /etc/warewulf/warewulf.conf that would be helpful as well

**Comment by TerranWorks** [comment]
Digging into the source code, I think I can just add vmlinuz-linux to https://github.com/hpcng/warewulf/blob/main/internal/pkg/kernel/kernel.go#L21 to make it more arch compatible. I'll look in to making a pull request

**Comment by TerranWorks** [comment]
Thank you. That config file entry will make my dhcp install role a lot easier to write.

I'm trying to test out the change I made to the warewulf code. Do I need to uninstall and then reinstall warewulf to make these changes appear or is their a rebuild command or something. It might be obvious I'm not sure

**Comment by mslacken** [comment]
Fixed in #315
