### ISSUE TITLE
`wwctl configure tftp` enables tftp.socket with `enabled: false` set in `warewulf.conf`

### ISSUE THREAD

**Issue by griznog** [hpcng/warewulf#319]
With this in `/etc/warewulf.conf`:

```
tftp:
  enabled: false
  systemd name: tftp
```
I expected `wwctl configure tftp` to set up the files in `/var/lib/tftpboot/warewulf` but not enable the `tftp` socket which on my system is already in use by `dnsmasq`.  When I run the command, this happens:

```
[root@lepomis warewulf]# wwctl configure tftp
Enabling and restarting the TFTP services
Created symlink /etc/systemd/system/sockets.target.wants/tftp.socket → /usr/lib/systemd/system/tftp.socket.
```

**Comment by aspfate** [comment]
This issue was fixed in #440.
You can close this issue. @griznog
