### ISSUE TITLE
wwctl serves empty files instead of error messages

### ISSUE THREAD

**Issue by jlinford** [hpcng/warewulf#32]
If the system overlay isn't built, the client gets an empty file from the controller.  It would be helpful to get an error message instead that suggests rebuilding the system overlay via `wwctl overlay build -s -a`

```
iPXE> imgfetch --name overlay-system  ${base}/overlay-system/f4-03-43-fe-90-01
http://10.1.232.194:9873/overlay-system/f4-03-43-fe-90-01... ok
iPXE> imgstat
f4-03-43-fe-90-01 : 14791168 bytes [EFI] [SELECTED] "rootfstype=tmpfs"
container : 72456645 bytes
kmods : 84094976 bytes
overlay-system : 0 bytes
iPXE> 
```

**Comment by gmkurtzer** [comment]
We are sending an HTTP error 404 if the system overlay isn't found. Can you do that `imgfetch` again while looking at `/tmp/warewulfd.log`?

**Comment by gmkurtzer** [comment]
I think this might be an error with iPXE. Have we confirmed if this is just on ARM?

**Comment by gmkurtzer** [comment]
I don't think this is fixable. I've experienced it as well. Warewulfd is properly sending an HTTP error code, but iPXE isn't responding to it properly. Gonna close with a can't fix.
