### ISSUE TITLE
IPXE configuration doesn't generate

### ISSUE THREAD

**Issue by TerranWorks** [hpcng/warewulf#325]
I'm experimenting with a warewulf arch cluster and I'm most of the way through the process, but no IPXE configurations are being generated in /var/lib/tftpboot/warewulf/ipxe. From the documentation, it seems like they should be generated automatically but maybe I missed something.

**Comment by griznog** [comment]
Those will show up in `/etc/warewulf/ipxe` or wherever that location got pointed to when building. They'll be sent to the node by `warewulfd` after `DHCP sends the URL to the node during network configuration. The stuff placed in `tftpboot/warewulf` are the different pxe shims for each architecture.

**Comment by TerranWorks** [comment]
it seems like the only files in my /usr/lib/etc/warewulf/ipxe(that my warewulf directory) are bigimage.ipxe, default.ipxe, and unconfigured.ipxe. I assume when I create a new node a file is supposed to be generated there which is named using the node's mac address like it was in warewulf3. Do I have to do something like the old wwsh update ipxe or should it be automatic? I wouldn't be surprised if arch is being weird about something.

**Comment by griznog** [comment]
Those are templates which get processed dynamically by `warewulfd` and the result sent to the nodes. You can fake the request with `wget` or `curl` to see what the result looks like.

**Comment by TerranWorks** [comment]
Thank you. I'm having another issue but I'll hop over to the Slack for that. I've been trying to get on slack but the link on the warewulf website seems to be broken. I already made an issue about it.

Do I need an invitation to join the Warewulf Slack channel?

**Comment by griznog** [comment]
Posting in this issue as well, in case someone finds this in a search and is looking for the invitation link for the hpcng slack.

https://join.slack.com/t/hpcng/shared_invite/zt-qda4h1ls-OP0Uouq6sSmVE6i_0NrWdw
