### ISSUE TITLE
Provisioning Security with separated PXE boot network

### ISSUE THREAD

**Issue by timehlers** [hpcng/warewulf#336]
Hello,

on https://warewulf.org/docs/enchiridion/security you wrote:

The best way to secure the provisioning process is to enact a vLAN used specifically for provisioning. Warewulf supports this [...]

I don't understand how this works and I think it is in the current state (4.2.0) not possible to secure Warewulf through a separated VLAN. Let's say you have 2 interfaces with networks 192.168.200.0/24 and 192.168.201.0/24. The first one is the one you use for provisioning and you don't want to use it after provisioning is finished, so the user cannot access it on a booted node.

Warewulf binds the wwctl-Daemon on 0.0.0.0, so the Daemon is reachable on all interfaces *and* it also serves everything on *all* interfaces like container, kmods and overlay-system. Only overlay-runtime is secured through allowing only source ports <1024 (which is a different security layer).

And *if* Warewulf would only bind on the interface with 192.168.200.0/24, how would you keep sync via wwclient? I think in addition to the source port security of overlay-runtime, we need a restriction of container, kmods and overlay-system to the provisioning interface to be secure (or better to the provisioning interfaces, we plan to have multiple clusters in different VLANs).

Or am I on the wrong track?

Thanks

Tim Ehlers

**Comment by griznog** [comment]
I've always considered the dedicated provisioning network to be more of a dedicated management network, sending provisioning, scheduler, `clush` from the master, etc. traffic, over that network and reserving any IB or high speed Ethernet interconnects for storage and MPI or other job communication. As such I've never considered impact of only provisioning and then completely dropping the network from the node. 

The question for me is, what is the provisioning network being protected from which originates from userspace? Would it be sufficient to leave it up for node management traffic and block user access via per-node outgoing firewall rules? 

Also it is possible to abandon `wwclient` after node boot, I run my cluster/nodes that way and handle the configuration stuff `wwinit` and `wwclient` do outside of Warewulf. If you remove the need to contact the warewulf master post-boot, then it's trivial to drop the provisioning network from the booted node config. Scary for me as having that guaranteed-to-work network around for troubleshooting is a warm safety blanket, but if it was a hard requirement it can be done. There is the problem that even if the network is dropped from the nodes network config, the link is still connected so a malicious user with elevated privileges could just bring the link back up and configure it. To be truly secure there'd have to be a layer added that would disable the network link from the master, maybe shutdown the switch port?, and somehow also know when to re-enable it when a reboot/provision was necessary. This is the point where Rube Goldberg enters stage right. 

To be able to drop the provisioning network and keep `wwclient` functionality would require a layer of authentication/access control to be added for all the post-boot contact to warewulf over the non-provisioning network. That also seems non-trivial to do well.

**Comment by mslacken** [comment]
There is a additional layer of security with the asset tags, which can be set per node and can only be read out, by the root user.
But yes, warewulf pretends that you network is secure, if not you will run into problems.
