### ISSUE TITLE
Container import generates empty image on Arch

### ISSUE THREAD

**Issue by TerranWorks** [hpcng/warewulf#346]
When I run the container import command it completes without error but the resulting container image is empty. I discovered that that the [find command](https://github.com/hpcng/warewulf/blob/main/internal/pkg/container/build.go#L55) was failing but the error wasn't being reported. It looks like find doesn't recognize the `` -xautofs `` and with more research it doesn't seem to exist in the most recent version of [gnu find](https://www.gnu.org/software/findutils/manual/find.pdf). My find version of find is `` find (GNU findutils) 4.9.0 `` btw.

**Comment by TerranWorks** [comment]
I've been running the command with the --debug option and then copy pasting the last command and manually running it without the -xautofs option and that has been working. Strangely, I just removed the option from the warewulf code and tried to re-import the container and it built a 1.2G (as opposed to the 4k i was getting before) but I'm getting a format error when I try to boot it which I wasn't getting when I ran the command manually.

**Comment by mslacken** [comment]
So yes, ist not checked if there was an error in the external find command. This whole section is a bit messy, as not only `find` is called externally, but also `cpio`. As we do not intend to have go to create the cpio archives (cpio is needed to boot the kernel), this code section will most likely stay in that state.
The `-xautofs` is more maent to eventually catch some corner cases, and I will remove it, as I was not aware that there are `find` versions without it. Thanks bringing this up.
The format error is odd, where exactly did you get it?

**Comment by TerranWorks** [comment]
I was getting it during the boot process when ipxe was trying to get the kernel image
