### ISSUE TITLE
Ubuntu 20.04 - Failed to restart dhcpd.service: Unit dhcpd.service not found

### ISSUE THREAD

**Issue by mrpg99** [hpcng/warewulf#355]
Hi ,

Warewulf 4 latest stable release, should it work with Ubuntu 20.04?

running:  

wwctl configure --all

gets me : 

################################################################################
Configuring: DHCP
Writing the DHCP configuration file
Enabling and restarting the DHCP services
Failed to restart dhcpd.service: Unit dhcpd.service not found.
ERROR: failed to configure dhcp: failed to start: failed to run start cmd: exit status 5

i.e the dhcp server systemd service on Ubuntu is called isc-dhcp-server not dhcpd

Br
Patric

**Comment by MatthewHink** [comment]
In warewulf.conf set

```
dhcp:
   systemd name: isc-dhcp-server
```

It should work. Default location is /usr/local/etc/warewulf.conf

**Comment by mrpg99** [comment]
Thanks for your reply.

I did not have a /usr/local/etc/warewulf/warewulf.conf

so i created it, and it now looks like : 

cat /usr/local/etc/warewulf/warewulf.conf
dhcp:
systemd name: isc-dhcp-server

however i still get 

wwctl configure --all
################################################################################
Configuring: DHCP
Writing the DHCP configuration file
Enabling and restarting the DHCP services
Failed to restart dhcpd.service: Unit dhcpd.service not found.
ERROR: failed to configure dhcp: failed to start: failed to run start cmd: exit status 5

**Comment by mslacken** [comment]
Did you check if the config is under `/etc/warewulf/warewulf.conf`?

**Comment by mrpg99** [comment]
> Did you check if the config is under `/etc/warewulf/warewulf.conf`?

That was it! many thanks its working now!

Br
Patric
