### ISSUE TITLE
Unit tests not running in CI.

### ISSUE THREAD

**Issue by MatthewHink** [hpcng/warewulf#369]
Not sure what happened here, but I can fix this. Doesn't look like I have permissions to fill out the assignees field either.

See here https://github.com/hpcng/warewulf/runs/5874333550?check_suite_focus=true
We are doing `make all` which does not run tests. We may want go vet as well.

**Comment by anderbubble** [comment]
@MatthewHink you still up for doing this?

**Comment by mslacken** [comment]
This isn't a bug

**Comment by anderbubble** [comment]
@mslacken do you mean to say this is intended behavior, or just that it's not a code bug?

**Comment by mslacken** [comment]
You made the PR which I merged in which `make all` won't run the tests. So its the intended behavior.
