### ISSUE TITLE
incorrect path in wwctl kernel import

### ISSUE THREAD

**Issue by bdphipps** [hpcng/warewulf#374]
[VERBOSE]    : Looking for kernel at: /var/lib/warewulf/chroots/rocky-8/rootfs/lib/mmodules/4.18.0-348.20.1.el8_5.x86_64/vmlinuz

The command should be looking for the kernel at: /var/lib/warewulf/chroots/rocky-8/rootfs/lib/modules/

not: /var/lib/warewulf/chroots/rocky-8/rootfs/lib/mmodules/

https://github.com/hpcng/warewulf/blob/main/internal/pkg/kernel/kernel.go
lines 27 and 28

**Comment by mslacken** [comment]
There was obliviously a typo. Fixed it. Thanks for finding this.
