### ISSUE TITLE
'wwctl node ready' not functional in 4.3.0 rc1 

### ISSUE THREAD

**Issue by bdphipps** [hpcng/warewulf#375]
Using tab completion of the command ready is on the list of options for wwctl node:
# wwctl node
add      console  delete   list     ready    sensors  set      status

When the option is added to the command, it fails to execute and outputs the help/usage message:
# wwctl node ready

Management of node settings. All node ranges can use brackets to identify
node ranges. For example: n00[00-4].cluster[0-1] will identify the first 5 nodes
in cluster0 and cluster1.

Usage:
  wwctl node COMMAND [OPTIONS]

Available Commands:
  add         Add new node to Warewulf
  console     Connect to IPMI console
  delete      Delete a node from Warewulf
  list        List nodes
  sensors     Show node IPMI sensor information
  set         Configure node properties
  status      View the provisioning status of nodes

Options:
  -h, --help   help for node

Global Options:
  -d, --debug     Run with debugging messages enabled.
  -v, --verbose   Run with increased verbosity.

Use "wwctl node COMMAND --help" for more information about a COMMAND.

[root@mtcadm02 ~]#

**Comment by mslacken** [comment]
There is no `wwctl node ready ` available any more. I assume that 
* your running shell is up for so long, that you have sourced an old `bash_completion/warewulf`, which still has this command.
* as the place of `bash_completion/warewulf` changed in the last commits, or may be now even `bash_completion/wwctl`, the deprecated file was not overwritten by the new one. So try to find the old bash_completion (under `/etc/, `/usr/local/, `/usr/lib` are suspicious places and delete the file there.

Both things happen often to me and drove me nuts.

**Comment by bdphipps** [comment]
Shouldn't the previous bash_completion be found and removed when the package that installed it is removed from the system?

**Comment by mslacken** [comment]
Under normal circumstances yes, but the location of the `bash_completion` can be changed during the build. So the command
```
BASHCOMPDIR=/foo make install
```
will install the  bash_completion to `/foo`. The default of `BASHCOMPDIR` is '/etc/bash_completion.d`, but as said, this changed in the last months.
