### ISSUE TITLE
use `nil` instead for node/profile list commad

### ISSUE THREAD

**Issue by mslacken** [hpcng/warewulf#390]
The output of `wwctl node/container list -a` should be changed in such way, that we display `nil` instead of `--` .
This fixes the problem of using `UNSET` or `UNDEF` to delete values, as `--` is parsed out by cobra, which `nil` wouldn't.

**Comment by anderbubble** [comment]
This should be pretty easy to implement: the `--` string is already just defined as a const or similar. I think then it'd just be a matter of adding `nil` to the list of strings that will unset a value. (I think we should retain `UNSET`/`UNDEF` for backwards-compatibility.) Agreed?

**Comment by mslacken** [comment]
`nil` can now be used to UNDEF values
