### ISSUE TITLE
Change "default" network device to another term.

### ISSUE THREAD

**Issue by jcsiadal** [hpcng/warewulf#391]
We're overloading the term "default" in the configuration, and this can be confusing, especially when trying to discuss an issue.

Default means failure, fail-over, or fall-back.  In computer terminology, "a preselected option adopted by a computer program or other mechanism when no alternative is specified by the user or programmer"

For example, the default boot network would be the last one tried, if all of the others failed. We currently define it as the opposite. This:
```
    network devices:
      eth0:
        default: "true"
```
Needs to be changed to something like this:
```
    network devices:
      eth0:
        primary: "true"
```

**Comment by mslacken** [comment]
was fixed in 4.3.0
