### ISSUE TITLE
Cannot delete network name in a profile

### ISSUE THREAD

**Issue by jcsiadal** [hpcng/warewulf#395]
Cannot determine a way to remove the default network using wwctl.
```
    network devices:
      default: {}
      eth0:
        type: ethernet
        ...
```

The obvious way produces an error, which appears to be a bug.
```
[root@frontend ~]# wwctl profile set default --netdel --netname default
[ERROR]      : You must include the '--netname' option
```

**Comment by mslacken** [comment]
@jcsiadal can you please check #405 fixes this issue

**Comment by jcsiadal** [comment]
#400 fixes this issue, as well as a few others. I don't have permission to manually link issues to PRs.
