### ISSUE TITLE
Compute node fstab error

### ISSUE THREAD

**Issue by jcsiadal** [hpcng/warewulf#396]
Enabling the /opt  mount in warewulf.conf producing the following fstab entries on compute nodes:

192.168.1.100:/home /home nfs defaults 0 0
192.168.1.100:/opt /opt nfs  0 0

The /home entry is setup correctly, but the /opt entry is missing the arguments parameter, because mount options in warewulf.conf is empty unless the user updates it. If NFS mount options is blank, whitespace, or unassigned, it should default to "default".

**Comment by mslacken** [comment]
Closed with #420
