### ISSUE TITLE
documentation is missing a method to toggle node 'Disabled' status

### ISSUE THREAD

**Issue by rhenwood-arm** [hpcng/warewulf#40]
Looking at this documentation:
https://github.com/ctrliq/warewulf/blob/main/docs/docs/wwctl/node.md
it appears to be missing a mechanism to toggle the node `Disabled` status.

**Comment by gmkurtzer** [comment]
Just so I'm clear, are you asking for a documentation fix to match the code or a code fix to match the documentation?

Thanks!

**Comment by rhenwood-arm** [comment]
I suggest that the code should be updated to support toggling disabled (or to avoid a double negative it could be called 'enabled'?), and the documentation should be updated to record this functionality.

**Comment by gmkurtzer** [comment]
So it is actually funny, aside from reading and printing the "Disabled" tag, Warewulf isn't doing anything else with it. So I'm going to remove the option as it isn't actually very useful.

**Comment by gmkurtzer** [comment]
It has been removed. Thanks for spotting the discrepancy!
