### ISSUE TITLE
problem mounting nfs shares during boot

### ISSUE THREAD

**Issue by mrpg99** [hpcng/warewulf#402]
Dear Sir/Madam,

I am setting up a small cluster where all servers will run Ubuntu 20.04
It is not mounting nfs exported directories on startup 

root@node001:~# cat /var/log/syslog |grep /home
Apr 20 20:29:30 wolfgang-cpu01 systemd[1]: Mounting /home...
Apr 20 20:29:30 wolfgang-cpu01 systemd[1]: Failed to mount /home.

in /etc/warewulf/warewulf.conf i have in the nfs section : 
nfs:
  systemd name: nfs-kernel-server
  exports:
  - /home
  - /var/warewulf

There are some tricks on Ubuntu to get nfs exports to mount on boot, asking the system to wait until the server has an ip address before mounting the nfs export, like :

x-systemd.after=network-online.target,_netdev 0 0

I have tried setting these options in the chroted container, but it does not apply.

where do i enter nfs mounting options?

Br
Patric

**Comment by mrpg99** [comment]
Forgot to mention that the exports mount fine when i mount them manually after boot  with mount -a :

df -h 
mount -a :

Filesystem                 Size  Used Avail Use% Mounted on
devtmpfs                  1002G     0 1002G   0% /dev
tmpfs                     1002G  2.5M 1002G   1% /run
tmpfs                     1002G     0 1002G   0% /dev/shm
tmpfs                      5.0M     0  5.0M   0% /run/lock
tmpfs                     1002G     0 1002G   0% /sys/fs/cgroup
tmpfs                     1002G     0 1002G   0% /run/shm
tmpfs                      201G     0  201G   0% /run/user/0
192.168.8.2:/home           63G   13G   47G  21% /home
192.168.8.2:/var/warewulf  7.9G  3.4G  4.1G  45% /var/warewulf

**Comment by mslacken** [comment]
Mount options can be set in `warwulf.conf` (at the time of this comment), so ubuntu specific options should go there.
