### ISSUE TITLE
Different path of dhcpd.conf

### ISSUE THREAD

**Issue by aspfate** [hpcng/warewulf#435]
dhcpd.conf has different path in different Linux's dist.
The path in openSUSE is /etc/dhcpd.conf.
Wether we should use warewulf.conf to specify dhcpd.conf path?

**Comment by mslacken** [comment]
The path can be modified by moving the template `dhcpd.conf.ww` to the right directory. The devel package under https://build.opensuse.org/package/show/network:cluster/warewulf4 has the template in the right directory.
What we can do here is to install `dhcpd.conf.ww` to right directory with `make install`, if a openSUSE like distro is detected.

**Comment by mslacken** [comment]
P.S.
For openSUSE you will also have to add the interface or network to `/etc/sysconfig/dhcpd`
