### ISSUE TITLE
Network device naming scheme

### ISSUE THREAD

**Issue by IngoMeyer441** [hpcng/warewulf#436]
This is more a question than an issue. I wonder how Warewulf v4 manages to disable the predictable name scheme for network devices. AFAIK, Warewulf v3 added the kernel parameters `net.ifnames=0 biosdevname=0` on boot, but this is no longer valid for Warewulf v4. Nevertheless, the old `ethX` naming scheme is used for network cards. How does this work?

**Comment by mslacken** [comment]
The magic happens with the template [10-persistent-net.link.ww](https://github.com/hpcng/warewulf/blob/main/overlays/wwinit/etc/systemd/network/10-persistent-net.link.ww) in which the network interface with the mac address known to warewulf4 is named after what you have configured for this specific netdev in warewulf4. 
In most cases this is `eth0` as this is the most common denominator as this device name was used in the prior 4.3.0 configurations.

**Comment by mslacken** [comment]
I always used `eth0`, but I just realized and tested than you can also set e.g. `lan0` for the primary interface.
