### ISSUE TITLE
[security] The path /warewulf/config should be protected.

### ISSUE THREAD

**Issue by aspfate** [hpcng/warewulf#446]
The path /warewulf/config shouldn't be accessable to everyone.
Sensitive infomations, i.e., IPMI account and password, are exposed.

``` bash
test@s11:/> ls -l /warewulf/
total 9648
-rw-r--r-- 1 root warewulf     192 Jun  8 17:09 config
drwxr-xr-x 2 root warewulf     180 Jun  8 17:09 init.d
-rwxr-xr-x 1 root warewulf 9870712 Jun  8 17:09 wwclient
-rwxr-xr-x 1 root warewulf     211 Jun  8 17:09 wwinit
```

**Comment by mslacken** [comment]
Yes these files shouldn't be readable per default.
I think you can change the _wwinit_ overlay permissions, that should fix it for your case.

**Comment by aspfate** [comment]
After chmod 600 /var/lib/warewulf/overlays/wwinit/warewulf/config.ww it work fine.
I used rpm package (from CI) to install warewulf.
The default permission is as follows
``` bash
c1:/var/lib/warewulf/overlays/wwinit/warewulf # ll
total 9648
-rw-r--r-- 1 root warewulf     294 Jun  1 23:58 config.ww
drwxr-xr-x 1 root warewulf     154 Jun  8 13:08 init.d
-rwxr-xr-x 1 root warewulf 9870712 Jun  1 23:58 wwclient
-rwxr-xr-x 1 root warewulf     211 Jun  1 23:58 wwinit
```
Should we set right permission to default?
Because some users may not take attention into this.
