### ISSUE TITLE
`wwctl node set $NODE --profile test` does not work

### ISSUE THREAD

**Issue by mslacken** [hpcng/warewulf#449]
In 4.2.0 onwards profiles can't be set via the command
```
wwctl node set $NODE --profile test
```
As workaround (under the assumption that $NODE has set the fault profile) following works:
```
wwctl node set $NODE --addprofile test
wwctl node set $NODE --addprofile default
```

**Comment by griznog** [comment]
Does this also address https://github.com/hpcng/warewulf/issues/427 ?

**Comment by mslacken** [comment]
> 

Yes, thanks for finding this
