### ISSUE TITLE
Upgrade path

### ISSUE THREAD

**Issue by ssgituser** [hpcng/warewulf#452]
Searching the documentation I cannot seem to find anything related to upgrading from 3.7 to the lastest 4.x release. Is this upgrade path supported? 

If it is supported where can I find the documentation on the recommended steps?

**Comment by anderbubble** [comment]
@ssgituser sorry to go so long without a response. Migrations from Warewulf 3 to Warewulf 4 are generally quite manual, and we don't have a straightforward procedure. We've successfully navigated it a time or two, but we expect it will always take a bit of bespoke help, given the difference between the two platforms and the amount of customization that often exists in existing Warewulf 3 deployments.

If you'd like some hands-on support with a migration, I suggest either [asking in the HPCng Slack](https://join.slack.com/t/hpcng/shared_invite/zt-qda4h1ls-OP0Uouq6sSmVE6i_0NrWdw) (for community support) or [getting in touch with CIQ](https://ciq.co/products/warewulf/) (for professional support).
