### ISSUE TITLE
Optionally configure/override compiled in paths in `/etc/warewulf/warewulf.conf`

### ISSUE THREAD

**Issue by griznog** [hpcng/warewulf#454]
Use case: I keep my chroot, overlay, provision and other local state related areas on a ZFS filesystem that is not part of the OS install (e.g. not using root on ZFS). When installing from RPM WW4 uses the rpm-standard locations for these. Currently I can workaround this in one of at least two ways:

1. Set the mountpoints for my ZFS locations to match the RPM, e.g. `zfs set mountpoint=/var/warewulf POOL/path/to/my/warewulf/localstate` (possibly repeating that if overlays, chroots, ... are on individual filesystems.)
2. Install from source setting PREFIX and all other variables to match the RPM install with overrides for my local directories as needed.

Neither of these is entirely ideal, mounting a secondary ZFS filesystem in a place normally assumed to be an OS disk breaks the basic assumptions about "normal" mounts for the OS disk/locations. Building from source with modified locations adds an extra step to upgrading and staying current and moves the knowledge of these locations out to a build/install process rather than keeping them in the warewulf config with all other warewulf related settings. 

The RFE then is to have these and other possibly interesting paths be configurable in `/etc/warewulf/warewulf.conf`. E.g.:

```
{
 warewulf:
    overlay path: "/path/to/overlays"
    chroot path: "/path/to/chroots"
    provisioning path: "/path/to/provision"
tftp:
    tftp root: "/path/to/tftpboot"
}
```

**Comment by anderbubble** [comment]
I discovered this had 4.4 in the title, so I've added it to the milestone for now.

**Comment by griznog** [comment]
Closing this as it is  a duplicate of #635
