### ISSUE TITLE
support for wwinit icfcg.ww for Infiniband network-scripts

### ISSUE THREAD

**Issue by BeHom** [hpcng/warewulf#457]
In the latest version 4.3.0-1.git_235c23c the setup of infiniband network with wwinit is limited.
The provided ifcfg.ww file did not contain a "TYPE" value for the network script, so rock-8 assumes a default "Type=Ethernet" .
However TYPE=Ethernet will not work for Infiniband. Entries in the corresponding node.conf will therefore not taken into account. 
You can of course modify the ifcfg.ww file under wwinit, but it seems a better way to do this is to include it in the standard distribution. 
Accoring to the source code netdev.Type is available <br>
Example: Add to ifcfg.ww  
{{ if $netdev.Type -}}
TYPE={{ $netdev.Type }}
{{ end -}}
<br>
The nodes.conf under nodes:<nodename>:network-devices can then look like:
      ib0:
        onboot: "true"
        device: ib0
        ipaddr: 192.168.1.9
        type: InfiniBand

Again, this is already possible, but the standard would help people get an HPC cluster up and running faster.

**Comment by mslacken** [comment]
Thanks for finding this.

**Comment by griznog** [comment]
This is related to https://github.com/hpcng/warewulf/issues/451, Type and other per-network settings need to be specified at a higher level rather than a per-node or per-device config.

**Comment by BeHom** [comment]
This are device specfic values and not global network attributes. Such values are well kept in profiles (nodeprofiles:network devices:) which are needed for a specific device and are set as default for all corresponding nodes.

**Comment by BeHom** [comment]
Maybe I missed your point. Typically, one has several networks with different settings for the respective NICs. Within the specific network there are of course no other network types but certainly other per node NIC ip-addreses and perhaps device names.

The concept of Warwulf 4, as I currently understand it, is based on profiles that describe the common features of a cluster or parts of a cluster, e.g. netmask, type, gateway or MTU of the respective network interfaces. The node specification describes the node details that are specific to the node e.g. the IP address of the individual network interfaces. e.g settings like netmask come from Profile section in nodes.conf, IP addresses from <nodename> section in nodes.conf.
Thus, the nodes.conf represents the description of the cluster nodes in yaml. 
In contrast, the warewulf.conf describes the setup of the SMS for warewulf.
Some of the parameters are also relevant for the cluster nodes, such as the IP address of the boot device. However, I think it makes sense to separate the configuration of the SMS from the configuration of the cluster nodes. 
One point, the parameters in warewulf.conf require a restart of e.g. DHCP, TFP or warwulf itself. 
For the parameters in the nodes.conf this does not apply. Depending upon setting the parameters can be taken over also in the current run. 
It all looks good to me. But I may also be overlooking important points.

**Comment by anderbubble** [comment]
Fixed in #576
