### ISSUE TITLE
Missing MTU value in netdev, wwctl profile and wwctl node

### ISSUE THREAD

**Issue by BeHom** [hpcng/warewulf#459]
The MTU parameter is often required for setting up a network connection in an HPC envrionment.
The current profile or node network configuration does not support this parameter. This means that the connection always falls back to the default MTU for wwinit. 

I think it makes sense to include the MTU parameter in the default configuration. 
It is generally possible to write your own ifcfg-xxx.conf in which the MTU is taken over. But from my point of view this breaks the concept of the central management of the nodes in the nodes.conf. The central and simple Mamagement of configuration parameters is however a substantial advantage of Warewulf (jm2c).

**Comment by griznog** [comment]
This is is related to https://github.com/hpcng/warewulf/issues/451, MTU (and other things) really need to be specified at a higher level rather than in a per-node config or tag.

**Comment by BeHom** [comment]
Not sure whether such big change is required. You can simple add MTU to default profile like netmask and Gateways. 
This will than apply to all nodes with that profile. 

PS: Two different gateways defined in the network example https://github.com/hpcng/warewulf/issues/451,  seem strange to me.

**Comment by griznog** [comment]
> Not sure whether such big change is required. You can simple add MTU to default profile like netmask and Gateways. This will than apply to all nodes with that profile.

The RFE is for 4.4, as this is definitely a major change/improvement. Abstracting the network out to a separate config tree has a number of benefits, the main one relevant here is to simplify the per-node configs by removing a lot of redundancy and potential for error (e.g. did I update MTU on every node/device in this network? That potential error goes away if MTU is a per-network setting.) 

> PS: Two different gateways defined in the network example #451, seem strange to me.

Any host in multiple networks can potentially have multiple gateways, one of these may be the `default` gateway (although a default gateway is not required) and the rest are more likely to be used for specific static routes.

**Comment by BeHom** [comment]
Fair enough and good dicussion. 
With regard to network management, I think it would be unfortunate if you had to edit two files to implement a network setting. While you can customize the wwinit template ifcfg.ww to your needs you have always to check both the node.conf as well as the ifcfg.ww for changes. Also updates that perhaps overwrite the wwinit ifcfg.ww template become more complicated. 
Therefore, I would like to change the default wwinit ifcfg.ww template to be more general in terms of network tags. 

Instead of a change that only applies to the MTU, it would be better, in my view, to adopt network tags in general.

{{ range $key, $value := .Tags }}
{{ $key }}={{ $value }}
{{ end -}}

Since the MTU is only valid for a specific device, users should also specify the --netname. 
wwctl profile set default --nettag mtu=9000 --netname enp24s0

**Comment by BeHom** [comment]
At least I am not worried about the network tags. Since they are key values tags, you can choose whatever is needed. 
And of course, it is up to the user to use the right tag and template. 

Of course direct support of mtu inside warewulf network setting is prefered. 
Is #429 already implemented?

**Comment by mslacken** [comment]
At the moment the main branch is the branch on which the development happened. In the next days the development will happen in the devel branch and the main branch will always contain the last stable version.
As soon as the devel branch is the new standard branch, I will merge #429, it just has some internal changes to the overlay creation which I implemented too late to go into the 4.3.0 release.

**Comment by anderbubble** [comment]
@mslacken is this closed by https://github.com/hpcng/warewulf/pull/549?

**Comment by mslacken** [comment]
Yes its closed
