### ISSUE TITLE
Top of documentation titled "Enchiridion" in TOC

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#472]
Maybe it's something I'm missing, but the first TOC entry at is labeled "Enchiridion." This seems incorrect to me; but maybe it's a reference or joke I'm missing?

https://warewulf.org/docs/

![Screen Shot 2022-06-24 at 11 19 58 AM](https://user-images.githubusercontent.com/350294/175611197-8131f460-5186-4ecc-9520-d8cc50ba980e.png)

**Comment by MatthewHink** [comment]
This is part of Warewulf until the owner says it isn’t

**Comment by anderbubble** [comment]
Guess so! 😄
