### ISSUE TITLE
Incorrect permissions on resolv.conf

### ISSUE THREAD

**Issue by ondrejtichacek** [hpcng/warewulf#494]
The import of a built docker image into warewulf triggers synchronization of `/etc/resolv.conf` from the host to the container. However, the permissions are incorrect after synchronization. The content is synchronized correctly. The permission in the host are 644, while in the image they are 700.

Is there any reason, why this is done at the image import level and not overlay level?

Thanks!

**Comment by mslacken** [comment]
There is no overlay level currently in warewulf.  But as ``resolv.conf`` is the only file copied in at container it sounds sensible to find another   solution to handle resolv.conf.

**Comment by anderbubble** [comment]
@mslacken I think the question is, why is `resolv.conf` brought into the container at build time, rather than included in the system/wwinit overlay like, e.g., `/etc/passwd`?

**Comment by mslacken** [comment]
In the original implementation the `resolv.conf` was a  bind mount to the `resolv.conf` of the host which failed miserably if it was not present in the container.
As I am working on the  import of `qcow2` and `raw` images to warewulf  I will take care of this.
