### ISSUE TITLE
`kmods.img` build fails when kernel differs from container

### ISSUE THREAD

**Issue by griznog** [hpcng/warewulf#501]
I've recently been trying to use a container that 

1. Has multiple installed kernels
2. Has kernels much newer than the kernel on the master node
3. Uses weak modules or adds a third-party module via `dkms`

When trying to import all kernels from such a container, `kmods.img` can only be built successfully on the kernel matching the installed kernel(s) on the master node. Digging deeper to see why, within a container with kernel-modules and firmware installed I found:

```
[root@frankie /]# cd /lib/modules
[root@frankie modules]# find 
4.18.0-372.16.1.el8_6.0.1.x86_64/ kabi-current/                     kabi-rhel81/                      kabi-rhel83/                      kabi-rhel85/                      
4.18.0-372.9.1.el8.x86_64/        kabi-rhel80/                      kabi-rhel82/                      kabi-rhel84/                      kabi-rhel86/                      
[root@frankie modules]# find 4.18* -type l -exec ls -al {} \;
lrwxrwxrwx. 1 root root 5 Jul 14 14:53 4.18.0-372.16.1.el8_6.0.1.x86_64/source -> build
lrwxrwxrwx. 1 root root 59 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/zzstd.ko.xz -> /lib/modules/4.18.0-372.16.1.el8_6.x86_64/extra/zzstd.ko.xz
lrwxrwxrwx. 1 root root 65 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/kmod-kvdo/uds/uds.ko -> /lib/modules/4.18.0-372.9.1.el8.x86_64/extra/kmod-kvdo/uds/uds.ko
lrwxrwxrwx. 1 root root 66 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/kmod-kvdo/vdo/kvdo.ko -> /lib/modules/4.18.0-372.9.1.el8.x86_64/extra/kmod-kvdo/vdo/kvdo.ko
lrwxrwxrwx. 1 root root 61 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/znvpair.ko.xz -> /lib/modules/4.18.0-372.16.1.el8_6.x86_64/extra/znvpair.ko.xz
lrwxrwxrwx. 1 root root 57 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/zfs.ko.xz -> /lib/modules/4.18.0-372.16.1.el8_6.x86_64/extra/zfs.ko.xz
lrwxrwxrwx. 1 root root 61 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/zcommon.ko.xz -> /lib/modules/4.18.0-372.16.1.el8_6.x86_64/extra/zcommon.ko.xz
lrwxrwxrwx. 1 root root 62 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/zunicode.ko.xz -> /lib/modules/4.18.0-372.16.1.el8_6.x86_64/extra/zunicode.ko.xz
lrwxrwxrwx. 1 root root 57 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/spl.ko.xz -> /lib/modules/4.18.0-372.16.1.el8_6.x86_64/extra/spl.ko.xz
lrwxrwxrwx. 1 root root 57 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/icp.ko.xz -> /lib/modules/4.18.0-372.16.1.el8_6.x86_64/extra/icp.ko.xz
lrwxrwxrwx. 1 root root 58 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/zavl.ko.xz -> /lib/modules/4.18.0-372.16.1.el8_6.x86_64/extra/zavl.ko.xz
lrwxrwxrwx. 1 root root 58 Jul 19 13:28 4.18.0-372.16.1.el8_6.0.1.x86_64/weak-updates/zlua.ko.xz -> /lib/modules/4.18.0-372.16.1.el8_6.x86_64/extra/zlua.ko.xz
lrwxrwxrwx. 1 root root 49 Jul 14 14:53 4.18.0-372.16.1.el8_6.0.1.x86_64/build -> /usr/src/kernels/4.18.0-372.16.1.el8_6.0.1.x86_64
```

The same effect of absolute links is also present in `/lib/firmware`

Given that these critical areas rely on absolute links, this seems like a broken way to get these things onto the node and creates a hard dependency on the master node being in lock step with the containers. 

I'm not sure when I started seeing this as I don't load `kmods.img` in my local `ipxe` scripts because I always add full kernel packages to them so I can add `dkms` packages, thus there's no need to have a separate `kmods.img`. But having looked at this now it seems to me the concept of using `kmods.img` is inherently flawed. For example if I want to provision nodes of another architecture I couldn't just import a container because the resulting `kmods.img` file would be subject to picking up contents from the wrong architecture. 

In the short term the ability to disable attempting to build `kmods.img` would be a nice feature as the current process copies the kernel, builds `kmods.img` and then places the version in the provision location. As long as the copy step works things are fine for me for booting, but the failure at the `kmods.img` step causes the version to not get put in place making `wwctl kernel list` show a version of 0 for all the kernels which failed at `kmods.img`. I took a look at the code for this and can just comment out the `kmods.img` stuff locally, but that didn't seem like a solution worthy of a PR :) 

griznog

**Comment by mslacken** [comment]
Seems to be fixed.
