### ISSUE TITLE
wwctl node set --profile accepts non-existent profile, leading to undefined behavior

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#504]
Recently I accidentailly used `wwctl node set --profile` to set a node to a non-existent profile. I was renaming a profile (from "default" to "openhpc") and subsequently edited the profile name in nodes.yaml to match what I had set the nodes to; but this appears to have broken detection of the kernel in the container configured with the profile.

Clearly this is an edge case, and I edited a config file out-of-band, so I don't necessarily expect warewulf to handle that case well; but it might be appropriate for warewulf to prevent setting a non-existent `--profile`.

**Comment by mslacken** [comment]
After editing `nodes.conf` you should always restart `warewulfd` as its caches the config and does so not rebuild the required images (which contain the kernel).

**Comment by anderbubble** [comment]
Understood. But it might still be good for Warewulf to warn when or prevent setting a node to a non-existent profile.
