### ISSUE TITLE
Merge overlays from multiple profiles

### ISSUE THREAD

**Issue by jmechalas** [hpcng/warewulf#507]
Warewulf supports multiple overlays for a profile, and it supports multiple profiles for a node, but if you try to apply more than one profile to a node, and those profiles each define an overlay, only the last profile's overlays get applied.

For example, if profile A defines overlay X, and profile B defines overlay Y, and I assign both profiles to a node like so:
```
node:
  profiles:
  - A
  - B
 ```
Then I only get overlay Y. I would expect to get both overlays X and Y (applied in the order they were defined).

**Comment by mslacken** [comment]
Although nodes can have multiple profiles assigned, there is no agreement or description I am aware of how this should behave. 
For overlays which are defined in profile and node, they get simply overwritten by the overlays defined in the host.
But having this different for multiple profiles sounds sensible.

**Comment by jmechalas** [comment]
> The only way I can think to do that is to guarantee that profiles are an ordered list and overlays in profiles and on the node are an ordered list

This is the sensible way to go, IMO. THen, as you say, items get applied in the order they are defined.

> Note I consider it a best practice to not have the same file managed by multiple overlays, 

Agreed, and `wwctl overlay build` should report an error (and abort) if it detects the same file in multiple overlays.

**Comment by anderbubble** [comment]
Closed by #952.
