### ISSUE TITLE
RFE: wwctl overlay render command to show how a template would be rendered for a given node

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#516]
It would be useful for there to be a `wwctl overlay render` command that would show how a given template would be rendered on a given node.

**Comment by mslacken** [comment]
Its there in the `developl` branch. Try
```
wwctl overlay show -r $NODE $FILE
```
You just might want to add a better commandline completion.

**Comment by anderbubble** [comment]
Oh, great! Thanks for pointing this out.

For future reference, looks like it was added in 53667157c5e49f20168f3f55176fa52f07825514.
