### ISSUE TITLE
IpmiWrite=false on the Default profile isn't sticking

### ISSUE THREAD

**Issue by jtoddowen** [hpcng/warewulf#520]
`wwctl --debug profile set default --ipmiwrite=false` responds with `Modifying profile: default  Node: default, Setting Ipmiwrite to false`.  The same debug output occurs without the default since I have no other profile.  Either way, when I follow up with `wwctl profile list default -a` `IpmiWrite` is `true`.

**Comment by jtoddowen** [comment]
Looking through some `nodes.conf` files, under the `default` profile I found `write: lanplus` just below `interface: lanplus` which was strange.  Each node included a `write: "false"` line I expressly added, so the net result was false; this was before attempting any UNDEF assignments.

**Comment by mslacken** [comment]
Can you please recheck with 4.4.0?

**Comment by mslacken** [comment]
Can't confirm this on actual development branch any more.
