### ISSUE TITLE
IpmiAddr=UNDEF produces runtime error

### ISSUE THREAD

**Issue by jtoddowen** [hpcng/warewulf#521]
Removing entries from the default profile was not working until I saw another post indicating UNDEF was the route to go.  This worked for IpmiUser, IpmiInterface, IpmiPass, but failed with `panic: runtime error: index out of range [0] with length 0`

**Comment by mslacken** [comment]
Can you please recheck with 4.4.0, as I can't reproduce

**Comment by mslacken** [comment]
Can't confirm this any more in actual development branch.
