### ISSUE TITLE
RFE: Import node configurations from WW3

### ISSUE THREAD

**Issue by gmkurtzer** [hpcng/warewulf#548]
I have received a few requests to ease the transition from WW3 to WW4, and one way to do that would be to be able to import node configurations. Perhaps something along the lines of:

```
# ssh warewulf3-host wwsh node show | wwctl node import --from-ww3
```

It might also be nice to be able to import from different formats as well (e.g. CSV, or other standard YAML)

**Comment by mslacken** [comment]
CSV import is now possible,. but not from a pipe.
