### ISSUE TITLE
Release of 4.4.0

### ISSUE THREAD

**Issue by mslacken** [hpcng/warewulf#558]
I have merged all pending pull request so that a 4.4.0 can be pre released. 
The changelog would need an update about the new API from @MatthewHink
Any comments on this?

**Comment by MatthewHink** [comment]
@mslacken This is a great point. I have comments in this commit. Would we like those in the changelog or something more succinct? https://github.com/hpcng/warewulf/pull/471

**Comment by mslacken** [comment]
> @mslacken This is a great point. I have comments in this commit. Would we like those in the changelog or something more succinct? #471

I think some lines in CHANGELOG.md would be great and a new file e.g. API.md with the contents of #471 would be helpful.
