### ISSUE TITLE
no documented method to change a node's profile.

### ISSUE THREAD

**Issue by rhenwood-arm** [hpcng/warewulf#58]
I've created a new profile with an updated OS. I want to change an existing node to now inherit my new profile, but the documentation does not include an obvious method to do so: 

https://docs.ctrliq.com/warewulf/docs/wwctl/profile

**Comment by rhenwood-arm** [comment]
Looking at the in-line documentation, there is: --addprofile (-p) and --delprofile (-r) which seem to do what I need.

**Comment by rhenwood-arm** [comment]
So, I think all that's needed here is to include  --addprofile (-p) and --delprofile (-r) on this page: https://docs.ctrliq.com/warewulf/docs/wwctl/profile

**Comment by gmkurtzer** [comment]
I just added the option `--profile` which will allow you put a comma delimitated list of profiles you wish to define for a particular node or set of nodes.

note: I also had to change some of the short options for the commands to make things more logical.
