### ISSUE TITLE
Container copy and rename

### ISSUE THREAD

**Issue by laytonjbgmail** [hpcng/warewulf#583]
In version 4.3 there is no way to copy a container and or rename it. I need this functionality so I can make a copy of my current container, rename the copy, and start experimenting with this renamed container. Therefore, I'm making a feature request.

Maybe something like

$ sudo wwctl container copy <container1> <container2>

This allows you to copy it and rename it at the same time. Without "container2" it just makes a copy with the name "container1-copy". If container2 exists, a message is written to stdout and the operation is cancelled.

To rename a container,

$ sudo wwctl container rename <container1_name> <container1_new_name>

There would likely need to be some limits on what you can name a container. Perhaps the command checks for that. If there is an illegal character, and error is written to stdout and the operation is cancelled.

Thanks!

Jeff

**Comment by griznog** [comment]
It'd be nice if this feature included a configurable way to set the command used to copy, in the default case an `rsync` of the chroot is sufficient, but a way to support filesystem based cloning, e.g. ZFS `snapshot & clone` to create the copy would be awesome. If the `wwctl container copy` command were configurable then this could be handled by the admin.

**Comment by anderbubble** [comment]
The copy functionality was implemented in #904. I think rename remains to be done, though.

**Comment by JasonYangShadow** [comment]
I will take a look at this feature.
