### ISSUE TITLE
Please add sudo to centos-8 Docker container

### ISSUE THREAD

**Issue by tcooper** [hpcng/warewulf#59]
When automating the deployment of a Warewulf v4 cluster (for example with Vagrant) certain `vagrant` commands attempt to use `sudo` inside the machine.

For example, the Vagrant command, `vagrant up <machine>` will attempt to ssh into container and use sudo to perform any provisioning steps specified for the machine using `sudo`. These always fail because `sudo` is not present.

For example...

```ruby
~/boxes/warewulf-vagrant on main !6 ?10 ❯ vagrant up cn0
Bringing machine 'cn0' up with 'virtualbox' provider...
==> cn0: Importing base box 'onyxpoint/empty'...
==> cn0: Matching MAC address for NAT networking...
==> cn0: Checking if box 'onyxpoint/empty' version '1.0.0' is up to date...
==> cn0: Setting the name of the VM: warewulf-vagrant_cn0_1618014203007_2463
==> cn0: Fixed port collision for 22 => 2222. Now on port 2200.
==> cn0: Clearing any previously set network interfaces...
==> cn0: Preparing network interfaces based on configuration...
    cn0: Adapter 1: nat
    cn0: Adapter 2: hostonly
==> cn0: Forwarding ports...
    cn0: 22 (guest) => 2200 (host) (adapter 1)
==> cn0: Running 'pre-boot' VM customizations...
==> cn0: Booting VM...
==> cn0: Waiting for machine to boot. This may take a few minutes...
    cn0: SSH address: 127.0.0.1:2200
    cn0: SSH username: vagrant
    cn0: SSH auth method: private key
    cn0: Warning: Authentication failure. Retrying...
==> cn0: Machine booted and ready!
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sed -i '/#VAGRANT-BEGIN/,/#VAGRANT-END/d' /etc/fstab

Stdout from the command:

Stderr from the command:
```

Running `vagrant` with the `--debug` option allows you to examine the cause of the failure and it is clearly caused by `sudo` not being present.

Here is an excerpt from the debug log of another command requiring `sudo`. The `vagrant reload` command will detect the OS inside the machine and execute the appropriate command to reboot it. For CentOS this amounts to `sudo shutdown -h now` (followed later by appropriate provider _power on_ semanitcs)...

```ruby
~/boxes/warewulf-vagrant on main !6 ?10 ❯ vagrant reload --debug cn0 2>&1 | grep "Detected: centos" -B5 -A30
  2819	DEBUG guest: Trying: centos
  2820	DEBUG ssh: Re-using SSH connection.
  2821	 INFO ssh: Execute: cat /etc/centos-release (sudo=false)
  2822	DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
  2823	DEBUG ssh: Exit status: 0
  2824	 INFO guest: Detected: centos!
  2825	DEBUG guest: Searching for cap: halt
  2826	DEBUG guest: Checking in: centos
  2827	DEBUG guest: Checking in: redhat
  2828	DEBUG guest: Checking in: linux
  2829	DEBUG guest: Found cap: halt in linux
  2830	 INFO guest: Execute capability: halt [#<Vagrant::Machine: cn0 (VagrantPlugins::ProviderVirtualBox::Provider)>] (centos)
  2831	DEBUG ssh: Re-using SSH connection.
  2832	 INFO ssh: Execute: ps -o comm= 1 | grep systemd (sudo=true)
  2833	DEBUG ssh: Exit status: 127
  2834	DEBUG ssh: stderr: bash: sudo: command not found
  2835
  2836	DEBUG ssh: Re-using SSH connection.
  2837	 INFO ssh: Execute: shutdown -h now (sudo=true)
  2838	DEBUG ssh: Exit status: 127
  2839	DEBUG ssh: stderr: bash: sudo: command not found
  2840
  2841	ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
  2842	Vagrant assumes that this means the command failed!
  2843
  2844	shutdown -h now
  2845
  2846	Stdout from the command:
  2847
  2848
  2849
  2850	Stderr from the command:
  2851
  2852
  2853	 INFO warden: Beginning recovery process...
  2854	 INFO warden: Recovery complete.
```

A solution to these problems with Vagrant is to install `sudo` into the Docker container that is pulled following the instructions in the [Warewulf Quickstart Guide for EL8](https://github.com/ctrliq/warewulf/blob/main/docs/docs/getting-started/quickstart-el8.md).

**Comment by tcooper** [comment]
Until this is resolved in the warewulf docker container you can find a workaround in [warewulf-vagrant/mgr/warewulf_container.sh](https://github.com/tcooper/warewulf-vagrant/blob/main/mgr/warewulf_container.sh).

**Comment by gmkurtzer** [comment]
The Warewulf base CentOS containers are meant to be as small as possible. Can you run a `dnf install sudo` from within the container after it is imported into Warewulf. Would that do the trick, or does this have to be within the Docker container itself?

**Comment by tcooper** [comment]
Yup... that would work and I have a better mechanism to create container using dnf into a clean chroot. Closing.
