### ISSUE TITLE
4.4.0rc2: wwctl profile set --comment asks about nodes when none are set up

### ISSUE THREAD

**Issue by jtoddowen** [hpcng/warewulf#600]
`wwctl profile set --comment "OpenHPC on Alpha" openhpc` returns `Are you sure you want to modify 1 node(s): [y/N]` when no nodes have even been set up.

**Comment by jtoddowen** [comment]
This appears to be part of the `profile` and `node` unification effort, so it looks like a minor glitch.

**Comment by anderbubble** [comment]
@jtoddowen I agree, this looks like just a logging output mistake. Should be fixed in #601.
