### ISSUE TITLE
Undocumented changes in node, profile cli arguments

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#602]
Conversation in Slack and CIQ recently identified that `--system` has become `--wwinit` in 4.4.0 release candidates. On further investigation, I see that there are _many_ changes to the node and profile arguments from #495.

I think we should discuss

- whether the current arguments are what we want going forward (including the removal of helper arguments like `--addprofile` and `--undiscoverable`)
- whether there should be a period of aliases for the old names being retained, perhaps with a deprecation warning

If this change remains, we at least need to update the web docs (already in need, regardless) and `CHANGELOG`.

**Comment by mslacken** [comment]
If we create aliases they should definitely come with deprecation warnings. Having `--system` and `--wwinit`  at the same time is too confusing in my eyes.

**Comment by anderbubble** [comment]
Closing in favor of #637.
