### ISSUE TITLE
wwctl nodes list == wwctl profile list

### ISSUE THREAD

**Issue by jtoddowen** [hpcng/warewulf#609]
`wwctl profile list` looks like it should listing default and all of your other profiles.  When looking for my nodes I typed `wwctl nodes list`; maybe this shouldn't work at all, but the output doesn't contain any nodes, just profiles.  I'm not sure what is correct, but this behavior seems inconsistent.

**Comment by anderbubble** [comment]
@jtoddowen what you indicated is not what I see.

```
$ sudo wwctl profile list 
PROFILE NAME         COMMENT/DESCRIPTION
================================================================================
default              This profile is automatically included for each node

$ sudo wwctl node list 
NODE NAME              PROFILES                   NETWORK
================================================================================
n1                     default                    default
```

In the above output, for profiles, I see my single `default` profile; and for nodes, I see my `n1` node, though it does also show the `default` profile because it is assigned to that node.

Can you provide some shell output to show what you mean?

**Comment by jtoddowen** [comment]
@anderbubble `sudo wwctl nodes list` and check the output.  Note that `nodes` is plural.

**Comment by anderbubble** [comment]
Oh, wow. Good catch, @jtoddowen! Thanks for pointing this out.

```
[janderson@rocky ~]$ sudo wwctl node list
NODE NAME              PROFILES                   NETWORK
================================================================================
n1                     default                    default

[janderson@rocky ~]$ sudo wwctl nodes list
PROFILE NAME         COMMENT/DESCRIPTION
================================================================================
default              This profile is automatically included for each node
```
