### ISSUE TITLE
What's the role of docker

### ISSUE THREAD

**Issue by LecrisUT** [hpcng/warewulf#61]
So one difference from the previous version that I noticed is that at least the vnfs are downloaded from docker. My question is how reliant is the new warewulf infrastructure on docker? Can we ignore it all together on the nodes? Is it now recommended that we install the applications on the nodes via docker? Is it just the VNFS that are provided by docker or are other services as well?

**Comment by rhenwood-arm** [comment]
@LecrisUT : I've only joined the Warewulf community during preparation of v4 - but I can offer my experience for what that's worth.

I am using Warewulf on AArch64 and in my case I want to avoid external resources/dependencies (like hub.docker.com). My understanding is that 'docker' (or probably more accurately VNFS, which uses a docker format) provides the User Space components for a node when Warewulf is booting. I have found it easy to avoid touching hub.docker.com by locally using singularity: `singularity build --sandbox <containername> <path to def file>`.

In my case, I built a CentOS8 'VNFS' for aarch64 on my local disk. I then copied it across to here: `/var/warewulf/chroots/<containername>/rootfs/` and Warewulf served it correctly to the node when it was booting. I assume the nodes don't use docker. Docker isn't included in my VNFS.

**Comment by LecrisUT** [comment]
Hmm it then sounds like the original design, just that the vnfs are hosted on docker. I'm looking forward to trying it out

**Comment by gmkurtzer** [comment]
Hi @LecrisUT!

Yes, that is exactly correct. In a nutshell, Warewulf has been doing containers for over 20 years! Now that the rest of the container ecosystem has "caught up" (and surpassed by orders of magnitude), we are leveraging standard containers as our VNFS. This means all of the standard method for building, securing, testing, and hosting containers is now supported by Warewulf. :)

You can use this as follows:

```
$ sudo wwctl container import docker://warewulf/centos-8 my_container
$ sudo wwctl container list
$ sudo wwctl container exec my_container /bin/bash
```

**Comment by gmkurtzer** [comment]
I'm closing this issue. If you have any other questions feel free to reopen or join us on Slack at http://www.hpcng.org.

Thanks!
