### ISSUE TITLE
Missing support for AArch64 containers

### ISSUE THREAD

**Issue by rhenwood-arm** [hpcng/warewulf#62]
I'm testing Warewulf on an AArch64 cluster. I am most interested in CentOS8. The aarch64 container is missing from the Warewulf docker hub here: https://hub.docker.com/r/warewulf/centos-8

In addition, I can't find the Dockerfile to build this container myself.

I prefer to use a locally build container and I singularity seems the ideal tool for this job. However, there isn't a centos-8 def file. I have crudely modified the Centos-7 file - which gives a working container - but the boot hangs after multiuser.target and doesn't get to the login screen. I'm working on this problem, but I think a known working centos-8 def file or the centos-8 DockerFile would help me.

Finding and verifying a working AArch64 container is a prerequisite for adding support for AArch64 containers.

**Comment by rhenwood-arm** [comment]
As a note for myself of my current work-around: I currently do:

`/usr/local/bin/singularity build --sandbox ./rootfs/ ./warewulf/centos-8.def`

and copying it across to: `/var/warewulf/chroots/<containername>/rootfs/`

**Comment by rhenwood-arm** [comment]
For completeness: after copying across, you need to do a `wwctl container build <containername>`

**Comment by tcooper** [comment]
Oh... and... do not use `-` (hyphen) in `<containername>`.

**Comment by gmkurtzer** [comment]
Richard "volunteers" to build a quickstart for AARCH64 including container generation and to integrate or update documentation.

**Comment by rhenwood-arm** [comment]
@odidev is working with me on a walk  thought. 

I would like to re-open the conversation about if warewulf should publish a container for any architecture. It seems that writing the 'quickstart' to omit using the pre-published container would avoid a maintenance burden for this project.

**Comment by mslacken** [comment]
@rhenwood-arm the actual 4.3.0rc2 has the ability to directly import docker tar balls via the `file://path/to/my/tar/ball` syntax, so you can use `buildah` or other container tools to create a container. Although the `apptainer --sandbox` way is also working, but as I always forget to cleanup the sanboxes.
BTW, There are ready to use openSUSE aarch64 containers under https://registry.opensuse.org/science/warewulf/leap-15.3/containers/kernel:latest

**Comment by anderbubble** [comment]
aarch64 containers are now being built automatically as part of the container build process. For example, see here: https://github.com/hpcng/warewulf-node-images/actions/runs/5920641656/job/16052172476
