### ISSUE TITLE
Failure message when successfully opening defaults.conf

### ISSUE THREAD

**Issue by NateCrawford** [hpcng/warewulf#625]
https://github.com/hpcng/warewulf/blob/a22996245c56c244e7ccd09a1f4989a8eb8502c2/internal/pkg/node/constructors.go#L82

Should this actually be "Opening defaults from file:"? 

The defaults.conf file appears to be successfully read, and the lines just below this correctly handle a missing file.

**Comment by mslacken** [comment]
Right, fixed this.
