### ISSUE TITLE
Short hostname in templates?

### ISSUE THREAD

**Issue by NateCrawford** [hpcng/warewulf#627]
I tried to find the proper way to get the short hostname (i.e. "hostname -s") into templated config files, but it looks like the FQDN is only available.

Would it make sense to split "Id, Hostname, and BuildHost" in TemplateStruct to host and domain components? Alternately, is there a way to define custom entries for templates? We used them heavily in older versions of Warewulf.

Side note: there is some redundancy here:
https://github.com/hpcng/warewulf/blob/a22996245c56c244e7ccd09a1f4989a8eb8502c2/internal/pkg/overlay/datastructure.go#L60-L64

**Comment by anderbubble** [comment]
@NateCrawford thanks for pointing out that redundancy. I'll check in on that.

Personally, I use `.Hostname` (or `.Id`) for the short hostname, and then expect the domain portion to come from `.ClusterName`.

**Comment by NateCrawford** [comment]
In this specific case, I'm trying to modify overlays/host/etc/hosts.ww to re-arrange the "Warewulf Server" section from:
local_network_IPaddr  warewulf  hostname.public_domainname

to:
local_network_IPaddr hostname.local_domainname warewulf

but on the warewulf server, all these give "hostname.public_domainname":
{{$.BuildHost}}
{{.BuildHost}}
{{.Hostname}}
{{.Id}}

and {{.ClusterName}} is empty.

  For regular compute nodes, the values for .Hostname and .Id shown by "wwctl overlay show --render $nodename debug /warewulf/template-variables.md.ww" are indeed the short hostname, and .ClusterName is filled. [Is there a way to choose the warewulf server as the render argument?]

**Comment by anderbubble** [comment]
Yeah, looks like there isn't a way to do that yet. But there should be.

Are you trying to change the entry for the host/server itself, or for the compute nodes in the host's/server's /etc/hosts?

If the compute nodes, then is ClusterName empty even when you iterate through the compute nodes, like at https://github.com/hpcng/warewulf/blob/development/overlays/debug/warewulf/template-variables.md.ww#L128?
