### ISSUE TITLE
GetB method ignores profile (altvalue) if node (value) unset

### ISSUE THREAD

**Issue by NateCrawford** [hpcng/warewulf#629]
https://github.com/hpcng/warewulf/blob/a22996245c56c244e7ccd09a1f4989a8eb8502c2/internal/pkg/node/methods.go#L200-L211

For network devices, I have the "default" network set as primary=true in the default profile, and a second "ib" network defined in an "infiniband" profile with primary=false. The node configs leave primary unset for all networks.

The /etc/hosts file should be generated with the short hostname appearing only for the default network, but as-is, it does not show on any host line.  [Work-around -->] Manually adding primary=true to the default network in the node config overrides as intended. 

For example, I added a comment in the template for each netdev:
     #{{$netdev.Primary.GetB}}, {{$netdev.Primary.Get}}, {{$netdev.Primary}}

results:
Node 1:
  default net: primary=true (node), true (profile)
     node1_ip node1-default node1-eth0 node1
     #true, true, {[true] [true] default []}
  infiniband: primary=unset (node), false (profile) 
    node1_ipoib node1-ib node1-ib0
     #false, false, {[] [false] infiniband []}

Node 2:
  default net: primary=unset(node), true (profile)
    node2_ip node2-default node2-eth0
     #false, true, {[] [true] default []}
  infiniband: primary=unset (node), false (profile)
    node2_ipoib node2-ib node2-ib0
     #false, false, {[] [false] infiniband []}

**Comment by mslacken** [comment]
Thanks for finding and diagnosing this issue. I think this should merged into 4.4.0 
@anderbubble whats your take on the merge?
