### ISSUE TITLE
copy and move commands for overlays

### ISSUE THREAD

**Issue by kivel** [hpcng/warewulf#63]
It would be nice to have commands like
`wwctl overlay cp -s default myFancyProfile`
to duplicate overlays directly with wwctl, likewise a move command might be useful.

**Comment by gmkurtzer** [comment]
So, the way that overlays should be used are to be cascading, meaning, there shouldn't be duplicate content.

**Comment by kivel** [comment]
OK, so similar to the _profile_?
In that case, we are at the same point as with _profile_, which one takes precedence? I guess the first in the list. So we'd need a way to re-organise them. `wwctl node set -S default,realtime,debian,test [node pattern]`, right?

**Comment by gmkurtzer** [comment]
Yes, this we absolutely need still!

**Comment by gmkurtzer** [comment]
You know, I completely read this wrong... Overlays aren't cascading, profiles are. We need that command to organize and sort profiles. Sorry for the misunderstanding.

So with that being said, your desire to copy a profile makes perfect sense!

**Comment by gmkurtzer** [comment]
Per the above referenced commit, I believe profiles can now be rearranged via the `wwctl node set` command with a comma delimitated list of profiles.

Also, to be clear, profiles are cascading, such that latter profiles could overwrite previous configurations and this does not apply (yet) for overlays.
