### ISSUE TITLE
Network Devices Not Being Provisioned

### ISSUE THREAD

**Issue by bindatype** [hpcng/warewulf#633]
Hi, 

I'm not sure this is an actual bug or pebkac but I think it is worth reporting. After booting any node only the loopback device is provisioned. The host is running rocky-9 and warewulf was built from git version:
```
wwctl version:	 4.4.0rc3-1.git_b63ad7b
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.4.0rc3-1.git_b63ad7b"
```
`ip a` show no devices, other than lo, and there are no ifcfg-ethx scripts in /etc/sysconfig/network-scripts. 
![Screenshot 2023-01-04 at 1 04 54 PM](https://user-images.githubusercontent.com/6185719/210632021-66acd450-667e-4aeb-b50e-d277e7d0c646.png)

![Screenshot 2023-01-04 at 2 14 48 PM](https://user-images.githubusercontent.com/6185719/210631934-e2c22781-5670-45cc-aacd-403f55c88a64.png)

However, the cards are definitely present; the NIC is working doing PXE boot and once the node is up and running I can login from the console and see them with `lspci` or `dmidecode`. 

My warewulf.conf and nodes.conf look like this, respectively:
```
[root@glc2 ~]# cat /usr/local/etc/warewulf/warewulf.conf
WW_INTERNAL: 43
ipaddr: 192.168.100.6
netmask: 255.255.255.0
#network: 192.168.100.0
warewulf:
  port: 9873
  secure: false
  update interval: 60
  autobuild overlays: true
  host overlay: true
  syslog: false
dhcp:
  enabled: true
  range start: 192.168.100.50
  range end: 192.168.100.99
  systemd name: dhcpd
tftp:
  enabled: true
  systemd name: tftp
nfs:
  enabled: true
  export paths:
  - path: /home
    export options: rw,sync
    mount options: defaults
    mount: true
  - path: /opt
    export options: ro,sync,no_root_squash
    mount options: defaults
    mount: false
  systemd name: nfs-server
```
and
```
[root@glc2 ~]# cat /usr/local/etc/warewulf/nodes.conf
WW_INTERNAL: 43
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
    cluster name: cerberus
    container name: rocky-8
    network devices:
      default:
        onboot: "true"
        device: eth0
        netmask: 255.255.255.0
        gateway: 192.168.100.5
        primary: "true"
nodes:
  node001.cerberus:
    discoverable: "false"
    profiles:
    - default
    network devices:
      default:
        hwaddr: 18:66:da:9d:b4:cd
        ipaddr: 192.168.100.50
        primary: "true"
  node002.cerberus:
    discoverable: "false"
    profiles:
    - default
    network devices:
      default:
        hwaddr: 18:66:da:9d:98:2d
        ipaddr: 192.168.100.50
        primary: "true"
```
And example node that exhibits this behavior looks like:
```
[root@glc2 ~]# wwctl node list -a node001.cerberus
NODE                 FIELD              PROFILE      VALUE
=====================================================================================
node001.cerberus     Id                 --           node001.cerberus
node001.cerberus     comment            default      This profile is automatically included for each node
node001.cerberus     cluster            default      cerberus
node001.cerberus     container          default      rocky-8
node001.cerberus     ipxe               --           (default)
node001.cerberus     runtime            --           (generic)
node001.cerberus     wwinit             --           (wwinit)
node001.cerberus     root               --           (initramfs)
node001.cerberus     discoverable       --           false
node001.cerberus     init               --           (/sbin/init)
node001.cerberus     asset              --           --
node001.cerberus     kerneloverride     --           --
node001.cerberus     kernelargs         --           (quiet crashkernel=no vga=791 net.naming-scheme=v238)
node001.cerberus     ipmiaddr           --           --
node001.cerberus     ipminetmask        --           --
node001.cerberus     ipmiport           --           --
node001.cerberus     ipmigateway        --           --
node001.cerberus     ipmiuser           --           --
node001.cerberus     ipmipass           --           --
node001.cerberus     ipmiinterface      --           --
node001.cerberus     ipmiwrite          --           --
node001.cerberus     profile            --           default
node001.cerberus     default:type       --           (ethernet)
node001.cerberus     default:onboot     default      true
node001.cerberus     default:netdev     default      eth0
node001.cerberus     default:hwaddr     --           18:66:da:9d:b4:cd
node001.cerberus     default:ipaddr     --           192.168.100.50
node001.cerberus     default:ipaddr6    --           --
node001.cerberus     default:netmask    default      255.255.255.0
node001.cerberus     default:gateway    default      192.168.100.5
node001.cerberus     default:mtu        --           --
node001.cerberus     default:primary    SUPERSEDED   true
```
and the kernel being run on the compute nodes is 
![Screenshot 2023-01-04 at 2 28 55 PM](https://user-images.githubusercontent.com/6185719/210634189-d4fde167-c792-443f-b26d-be3ee6bc50b8.png)

The ifcfg.ww overlay in wwinit looks like:
```
[root@glc2 ~]# cat /var/local/warewulf/overlays/wwinit/etc/sysconfig/network-scripts/ifcfg.ww
{{- $host := .BuildHost }}
{{- $time := .BuildTime }}
{{- $source := .BuildSource }}
{{range $devname, $netdev := .NetDevs -}}
{{- $filename := print "ifcfg-" $devname ".conf" }}
{{- file $filename }}
# This file is autogenerated by warewulf
# Host:   {{ $host }}
# Time:   {{ $time }}
# Source: {{ $source }}
TYPE={{ $netdev.Type }}
DEVICE={{ $netdev.Device }}
NAME={{ $devname }}
BOOTPROTO=static
DEVTIMEOUT=10
IPADDR={{ $netdev.Ipaddr }}
NETMASK={{ $netdev.Netmask }}
{{ if $netdev.Gateway -}}
GATEWAY={{ $netdev.Gateway }}
{{ end -}}
{{ if $netdev.Hwaddr -}}
HWADDR={{ $netdev.Hwaddr }}
{{ end -}}
{{ if $netdev.Type -}}
TYPE={{ $netdev.Type }}
{{ end -}}
ONBOOT=yes
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
{{ if $netdev.Ipaddr6 -}}
IPV6ADDR="{{ $netdev.Ipaddr6 }}"
{{ end -}}
{{ end -}}
```

I'm a bit at loss - if the mistake is on my part I cannot find it so I'm wondering if this is unexpected behavior. I've tried provisioning nodes via `wwctl node set ...` or `wwctl profile set ...` yet neither seem to work. I don't think this is a hardware or compatibility issue either; there are two warewulf clusters (3 & 4.2) running on identical hardware in adjacent racks. I'm happy to provide more debugging information. Thanks for your attention.

**Comment by griznog** [comment]
Is either `NetworkManager` or the old network-scripts package and `network` service enabled in the container?

**Comment by bindatype** [comment]
Hi, 

NetworkManager is installed and there is a .service file in /etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service. I'm not exactly sure what else to do when /sbin/init isn't the entry point. 

That being said, there's still no NICs provisioned. Please see attached screenshot - sorry, our jumpbox doesn't allow for copy and paste. 
![Screenshot 2023-01-04 at 4 40 17 PM](https://user-images.githubusercontent.com/6185719/210655253-04b072f6-7a26-4ac0-a3d8-9e12285a9867.png)

**Comment by mslacken** [comment]
As far as I see this, your kernel does not recognize the network interface itself or its has another name than `eth0`, which is possible but unlikely. Check the output of dmesg for any kernel messages regarding the interface name and rename the network device accordingly.

**Comment by bindatype** [comment]
Yup, that solved the problem. I upgraded the kernel from 4.18.0-372.13.1.el8_6 to 4.18.0-425.3.1.el8.x86_64 and installed kernel-headers, -devel, -modules, and -tools. After that and a reboot all network devices were found. 

I suppose I naively expected not to have to do that with a fresh container. Is that a reasonable assumption? The original container was pulled using:
`wwctl container import docker://warewulf/rocky:8 rocky-8`

**Comment by mslacken** [comment]
It depends on how often the container is updated. I think @anderbubble knows more about how often this happens for rocky containers.
As I am with SUSE I know that the leap container get automatically updated as soon as any of its packages is updated.

**Comment by anderbubble** [comment]
@bindatype I expect the fix was the addition of the kernel-modules package, which is something I have encountered myself before as well.

I'm actively in the process of updating the published example containers, and I intend to include kernel-modules in the future.

I'm glad you were able to get it working!
