### ISSUE TITLE
Request For Comment: Introducing CLA

### ISSUE THREAD

**Issue by ikaneshiro** [hpcng/warewulf#65]
Warewulf needs a CLA for the project. Please review and add comments on:
https://docs.google.com/document/d/1uaREO0Fke9rND6abjZtMf4ASou0Zaejtv4Yix7I3O8c/edit

**Comment by dtrudg** [comment]
Not strictly Warefulf Q but...

>This Agreement applies to all Contributions (as defined below) submitted by you to a project owned or managed by us (each, a “Project”).

This doesn't appear to be project specific to Warewulf, but could apply to all HPCng hosted projects. Is there intention to use this more broadly?

**Comment by ikaneshiro** [comment]
This CLA is currently general and could be used for other projects, but that something to be discussed and agreed upon by those communities as well as this one(since this is a draft atm). Ill add that to the agenda for the singularity community meeting next week and im certain this will be discussed in the warewulf community meeting as well.

**Comment by dtrudg** [comment]
Thanks @ikaneshiro - there's some difference between the response from @gmkurtzer on the doc..

> That is being discussed by the HPCng board of directors.

And yours...

> ... something to be discussed and agreed upon by those communities as well ...

So the meeting seems a good venue to bring it up 👍

**Comment by jfrey** [comment]
The same CLA was provided to Greg to present to the board.  When approved we'll integrate a CLA assistant to handle the collection of contributor signatures moving forward which we'll discuss for Singularity in that project meeting.

**Comment by dtrudg** [comment]
Thanks for the clarification - I look forward to the discussion. However, I'd strongly suggest that anything that might affect other projects like Singularity is raised in the Singularity Slack and mailing list etc. as soon as possible so its' possible for people to take a look at the document ahead of time, in order to have informed discussion.

**Comment by jfrey** [comment]
Please feel free to forward the issue and CLA appropriately.

Thanks!

________________________________

**Comment by gmkurtzer** [comment]
This will be proposed to the Warewulf development community meeting tomorrow and I expect to have a final thumbs up/down shortly thus after.

**Comment by gmkurtzer** [comment]
We are waiting for feedback and will hopefully make a decision by May 19th.

**Comment by pedroalvesbatista** [comment]
Everything is fine, cover much of cases in terms of Open Source Contributor Agreement. 

Maybe we can make some trimestral reviews and see whatelse could be added or/and excluded, so we keep an evolutionary model that could apply to all HPCng's projects umbrella (for sure, each community making its own suggestions and modification for its own cases).

**Comment by anderbubble** [comment]
@anderbubble is going to take this back to @gmkurtzer, in comparison with #886.

**Comment by anderbubble** [comment]
Closing this in favor of the now-merged #886.
