### ISSUE TITLE
User collision reporting is backward [WW 4.3]

### ISSUE THREAD

**Issue by jcsiadal** [hpcng/warewulf#650]
User collision with Rocky 8.6 frontend and Rocky 8.6 Docker import.

Error message is:
WARN   : uid(998) collision for host: unbound and container: polkitd

User unbound is actually on the container and polkitd is on the host.

Expected behavior is that the usernames should be reversed.

**Comment by anderbubble** [comment]
Thanks for reporting this, @jcsiadal. I'll confirm in my environment and look into a fix.

**Comment by anderbubble** [comment]
@jcsiadal confirmed, and I've got a PR in process.
