### ISSUE TITLE
Merged overlay lists for multiple node profiles

### ISSUE THREAD

**Issue by griznog** [hpcng/warewulf#652]
1. When multiple profiles are specified, the resulting set of overlays should be the union of the profile sets and node config values. 
2. The node config should allow a `not` operator, proposed characters are `!` or `^` to keep consistency with shell or regex syntax respectively. 

An example use case:

A role "common" specifies overlays `authentication,rsyslog,chrony,autofs,network`
A role "compute" specifies overlays `slurm,munge,gpu`
A node `web-01` specifies profiles `common,compute` and overlays `httpd,!slurm,!munge`

The resulting set of overlays assigned to the node should be:
`authentication,rsyslog,chrony,autofs,network,gpu,httpd`

Overlays should have no sort order as best practice is to never have two overlays modify the same file. Bonus if the `wwctl overlay build` command warned when multiple overlays touched the same file.

**Comment by anderbubble** [comment]
Closed by #952.
