### ISSUE TITLE
Failed to build/import kernel

### ISSUE THREAD

**Issue by josedev-union** [hpcng/warewulf#655]
### Version of Warewulf
```shell
# wwctl version
4.3.0-1.git_235c23c
```
### Expected behavior
I want to import kernel and set kernel override for centos-8 container.

I tried to provision a node using `warewulf/centos:8` image but it is failing with `Downloading Kernel Image: HTTP://xxx:9873/00:xx:xx:xx.. HTTP 4xx Client Error` at the node.
I found that the container doesn't have kernel. So tried to import kernel.
```shell
$ wwctl kernel list
KERNEL NAME                         KERNEL VERSION            NODES 
$ wwctl container list
CONTAINER NAME            NODES  KERNEL VERSION
centos-8                  1      
```
### Actual behavior

I tried to import kernel from head node but it failed.
```
$ uname -a
Linux 192.168.200.1 4.18.0-383.el8.x86_64 #1 SMP Wed Apr 20 15:38:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ wwctl kernel import $(uname -r)
Found kernel at: /boot/vmlinuz-4.18.0-383.el8.x86_64
ERROR  : Failed building kernel: Failed creating image for 4.18.0-383.el8.x86_64 drivers: /var/lib/warewulf/kernel/4.18.0-383.el8.x86_64/kmods.img: exit status 2
```
Also I tried import from container but same.
```shell
$ wwctl container list
CONTAINER NAME            NODES  KERNEL VERSION
centos-8                  1      
rocky-8                   1      4.18.0-372.13.1.el8_6.x86_64

$ wwctl kernel import  --container rocky-8 -D -v
VERBOSE: Looking for kernel version with pattern at: /var/lib/warewulf/chroots/rocky-8/rootfs/boot/vmlinuz-linux
VERBOSE: Looking for kernel version with pattern at: /var/lib/warewulf/chroots/rocky-8/rootfs/boot/vmlinuz-*
VERBOSE: Parsing out kernel version for /var/lib/warewulf/chroots/rocky-8/rootfs/boot/vmlinuz-4.18.0-372.13.1.el8_6.x86_64
VERBOSE: found kernel version [[/var/lib/warewulf/chroots/rocky-8/rootfs/boot/vmlinuz-4.18.0-372.13.1.el8_6.x86_64 4.18.0-372.13.1.el8_6.x86_64]]
VERBOSE: Looking for kernel at: /var/lib/warewulf/chroots/rocky-8/rootfs/boot/vmlinuz-linux
VERBOSE: Looking for kernel at: /var/lib/warewulf/chroots/rocky-8/rootfs/boot/vmlinuz-4.18.0-372.13.1.el8_6.x86_64
INFO   : Found kernel at: /var/lib/warewulf/chroots/rocky-8/rootfs/boot/vmlinuz-4.18.0-372.13.1.el8_6.x86_64
VERBOSE: Setting up Kernel
VERBOSE: Creating image for rocky-8 drivers: /var/lib/warewulf/chroots/rocky-8/rootfs
ERROR  : Failed building kernel: Failed creating image for rocky-8 drivers: /var/lib/warewulf/kernel/rocky-8/kmods.img: exit status 2
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

```

### How did you install Warewulf
https://warewulf.org/docs/development/contents/installation.html#binary-rpms
RPM

**Comment by anderbubble** [comment]
Thanks for getting in touch!

In general, you shouldn't need to import a kernel manually any more: kernels should be included in and automatically extracted from the container image when it's imported. I suspect you're running into issues because the centos-8 image is no longer maintained, following the end of support for centos-8 upstream.

I suggest switching to warewulf/rocky:8 in stead, which should work out-of-the-box. I've got some pending updates to improve that image, too; but I expect centos-8 will be removed rather than updated.

**Comment by eshivers** [comment]
@anderbubble Hello can you tell me how to use RHEL8 as a container image instead of Rocky8? Our system has a license with RHEL8 and it would be so much work to migrate over

**Comment by anderbubble** [comment]
@eshivers I don't have any experience building the container image with RHEL8; but you can follow the example at https://github.com/hpcng/warewulf/tree/development/containers/Docker/rockylinux-8 to try to make one.

**Comment by aspfate** [comment]
same issue;
opensuse 15 use verison 4.4.0-1.git_afcdb21, 
```
localhost:~ # wwctl kernel import $(uname -r)
Found kernel at: /boot/vmlinuz-5.14.21-150500.53-default
ERROR  : Failed building kernel: Failed discovering files for 5.14.21-150500.53-default drivers: /: lstat proc/22624/fd/7: no such file or directory
```
full debug output is below
[output.txt](https://github.com/hpcng/warewulf/files/11798489/output.txt)

**Comment by griznog** [comment]
See #501 , if your master doesn't have the same kernel installed (not necessarily running) that the container uses then the absolute symlinks related to teh modules, kernel and possibly firmware won't be able to resolve. This should only affect the `kmods.img` and you can comment it out in `/etc/warewfult/ipxe` for the `ipxe` script you are using. As long as all the modules are installed in the container, it'll work perfectly fine without the `kmods.img`.

**Comment by aspfate** [comment]
we use singularity build container, not import container from docker.
so we should manual import kernel with `wwctl kernel import $(uname -r)`
some driver installer only allowed with connect the hardwares, so we cannot build docker with hardware support kenerl modules.

**Comment by mslacken** [comment]
You can always install the kernel via zypper or FNF during the docker/singularity build and not manage it separately.
I hope we can fix this bug until the next release.

**Comment by mslacken** [comment]
You can always install the kernel via zypper or FNF during the docker/singularity build and not manage it separately.
I hope we can fix this bug until the next release.

**Comment by anderbubble** [comment]
@mslacken I'm unclear if there's anything left to do on this one. You mentioned a bug, but I'm not sure what the bug is. Can you clarify?

**Comment by anderbubble** [comment]
I'll close it for now, then.
