### ISSUE TITLE
Editing nodes via wwctl leads to wrong assignment of node parameters

### ISSUE THREAD

**Issue by BeHom** [hpcng/warewulf#663]
### Version of Warewulf

What version of Warewulf are you using? Run

`wctl version:   4.4.0-1.git_afcdb21
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.4.0-1.git_afcdb21"`

### Expected behavior

What did you expect to see when you do...?
wwctl node edit should modify the changed parameters and leave the unchanged parameters as they are.
It should not happen that the assignment of the parameters gets mixed up. 

### Actual behavior
Ones "wwctl node edit " used the order of parameters for the nodes changed.

What actually happened? Why was it incorrect?
E.g. hpc1 now boots the hpc2 parameters, hpc2 boots hpc3 node parameters, etc.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
don't use the wwctl nodes set, instead edit the nodes via ```wwctl node edit <host>```
neither ```systemctl restart warewulfd.service ``` nor ```wwctl configure --all``` did change the behavior.
### What OS/distro are you running

```sh
$ cat /etc/os-release

```
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7" ```

### How did you install Warewulf

Write here how you installed Warewulf. Eg. RPM, source.
dnf install ./warewulf-4.4.0-1.git_afcdb21.el8.x86_64.rpm

**Comment by BeHom** [comment]
Found the problem and it is layer 8 :-(
The problem was that I also assigned a HW MAC address for the second Ethernet network of the second node. 
However, this address corresponded to the MAC of the default network of the first node. 

Pick put paste ......

**Comment by anderbubble** [comment]
Thanks, @BeHom. If I'm understanding correctly, then, this isn't an issue with Warewulf, so I'll close this. But let me know if I've misunderstood.

**Comment by BeHom** [comment]
When I investigated the problem further, I found that any "hwaddr" in node.conf besides the ones for the default interfaces were causing problems as described above.
I deleted all of them and now it works. it looks kind of weird to me. The added mac addresses seem to confuse warewulf when it comes to which node settings should be booted. I suspect that the MAC addresses play a central role and several under one node contribute to this confusion. JM2C 
If MAC address play such a central role it might be worth to include a MAC sanity check.

**Comment by anderbubble** [comment]
Can you share a nodes.conf that had this issue? Did you have multiple interfaces all marked primary?

**Comment by BeHom** [comment]
Checked this weekend with the original failed nodes.conf with "hwaddr" tags for the 2nd interface.
2nd interface was not marked primary (no tag primary at all for these interfaces). 
However, was not able to reproduce the behavior. 
We'll be back if the problems come up again.
