### ISSUE TITLE
provide snponly ipxe build for efi

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#681]
We've seen multiple instances now where a native-driver EFI build of iPXE fails to boot, particularly on older hardware or in unusual network circumstances. In those instances, an snponly.efi build has resolved the issue.

I suggest that we should make snponly.efi available, and perhaps use it by default.

Further, EL9 provides `ipxe-bootimgs-x86` and `ipxe-bootimgs-aarch64` packages, which appear to provide all of these builds already:

```
[janderson@rocky apptainer]$ rpm -ql ipxe-bootimgs-x86 
/usr/share/doc/ipxe-bootimgs-x86
/usr/share/doc/ipxe-bootimgs-x86/COPYING
/usr/share/doc/ipxe-bootimgs-x86/COPYING.GPLv2
/usr/share/doc/ipxe-bootimgs-x86/COPYING.UBDL
/usr/share/ipxe
/usr/share/ipxe/ipxe-i386.efi
/usr/share/ipxe/ipxe-snponly-x86_64.efi
/usr/share/ipxe/ipxe-x86_64.efi
/usr/share/ipxe/ipxe.dsk
/usr/share/ipxe/ipxe.iso
/usr/share/ipxe/ipxe.lkrn
/usr/share/ipxe/ipxe.usb
/usr/share/ipxe/undionly.kpxe

[janderson@rocky apptainer]$ rpm -ql ipxe-bootimgs-aarch64
/usr/share/ipxe
/usr/share/ipxe/arm64-efi
/usr/share/ipxe/arm64-efi/snponly.efi
```

If Suse has an equivalent set of packages, I propose that we should just stop bundling ipxe binaries and bring these in as dependencies.

This is particularly a good fit with #651

**Comment by griznog** [comment]
Using `snponly.efi` solved a longstanding issue for me where ConnectX[5-6] cards in some nodes were getting set to 100 Mbps by the iPXE driver. With `snponly.efi` teh BIOS magic works great and I get full speed downloads of the container. Bonus that it doesn't have to work it's way through every adapter on nodes that have a lot of adapters. 

For large images it does still need `imgextract` support and support for the console would also be a nice thing to have, not sure if the upstream distro version enables either or both of those. 

griznog

**Comment by anderbubble** [comment]
Obsoleted by #784, as long as that's done.
