### ISSUE TITLE
Included static ipxe v1.21.1 lacks imgextract command

### ISSUE THREAD

**Issue by bschwark** [hpcng/warewulf#689]
### Version of Warewulf

4.4.0 release

### Issue

The included ipxe binaries in staticfiles are built from a v1.21.1 tag in the ipxe project that for whatever reason lacks code for the imgextract command. This causes the warewulf ipxe script to fall back to old-style initrd, which causes boot failures when container/overlay size exceeds 3GB. This can be seen by the following error message output by the Warewulf ipxe script when it tries to unpack the images:

"Image extract not supported in this iPXE, using standard initrd mode" (from default.ipxe).

default.ipxe attempts to do imgextract first due to its obvious advantages over initrd, so it seems that using it is desired - but the included ipxe binaries lack the support due to tag v1.21.1 from ipxe being broken for this purpose. ipxe-update.sh also specifies this tag, and would similarly rebuild 'lacking' ipxe binaries.

Issue is alleviated by building ipxe binaries from ipxe/main, which includes the code for the imgextract command.

### What OS/distro are you running

Rocky 8.7 x86_64

### How did you install Warewulf

Built RPM from source using included specfile

**Comment by mslacken** [comment]
Thanks for your bug report. 
A goal for the next warewulf release is to get rid of static ipxe binaries in the sources as its is problematic for distributors to ship binary blobs from somewhere of the internet. See #651 for reference, where the location of the ipxe binaries are configurable.  Rocky/Centos ship ipxe binaries as rpm packages and should be used in the future for this.
As work around you can compile the ipxe binaries with the script https://github.com/hpcng/warewulf/blob/d234f2744bfa2a9261ae1ec2f2c479ee746c3a04/ipxe-update.sh
I hope this is OK for you.

**Comment by bschwark** [comment]
ipxe-update.sh, as it currently stands, will still build 'broken(lacking imgextract)' ipxe binaries due to it explicitly pulling the v1.21.1 tag from the ipxe github.

I have worked around the issue by building my own ipxe binaries from the ipxe project main branch - utilizing distro-supplied ipxe packages seems like a logical step in the future, though it doesn't provide any assurance that vendors are building their ipxe binaries 'properly', either.

**Comment by anderbubble** [comment]
> it doesn't provide any assurance that vendors are building their ipxe binaries 'properly', either.

That's true; but better support in Warewulf for configuring which ipxe builds to use will make it easier to bring in your own build if you need.

**Comment by anderbubble** [comment]
@JasonYangShadow if we can get the build process updated to use the OS packages for this in stead, that's fine too; but I think it's still relevant to this case.

**Comment by JasonYangShadow** [comment]
@anderbubble shall I close this PR? I saw you opened another PR for this.

**Comment by anderbubble** [comment]
I think we should keep this issue open until a fix for #784 is implemented; but they should both be closed then.
