### ISSUE TITLE
'wwctl node edit' inconsistent state with warewulfd

### ISSUE THREAD

**Issue by altuck00** [hpcng/warewulf#691]
### Version of Warewulf

wwctl version:   4.4.0-1.git_afcdb21
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.4.0-1.git_afcdb21"

### Expected behavior

When making changes to the node configuration using `wwctl node edit` the changes will be immediately reflected by warewulfd and appropriate ipxe/image/overlays will be applied to nodes.

### Actual behavior

After editing node configuration with `wwctl node edit` nodes become unrecognized by warewulfd during the provisioning step and receive the default iPXE script.

### Steps to reproduce this behavior

Configure and deploy a node, then edit the node with `wwctl node edit` and reboot it.

### What OS/distro are you running

```
NAME="Red Hat Enterprise Linux"
VERSION="9.1 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.1 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/9/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

### How did you install Warewulf

Warewulf was compiled from afcdb21.

**Comment by anderbubble** [comment]
@mslacken I'm thinking that warewulfd isn't getting poked correctly when the edit is applied. Any ideas?

**Comment by mslacken** [comment]
The problem here is that the nodes are not modified with the edit command, but deleted and then redadded with the changed parameters. So this seems to be an unwanted side effect of this process.

**Comment by anderbubble** [comment]
@mslacken and @JasonYangShadow this is still an issue, even after #719 and after #780 and #781.

**Comment by anderbubble** [comment]
Demonstration of the issue as seen from the head node:

First, we have a node with hwaddr `de:ad:be:ef:00:00`.

```console

$ sudo wwctl node list -a n1 | grep hwaddr
  n1    default:hwaddr      --          de:ad:be:ef:00:00                                     
```

We can see that it produces a "Warewulf v4 now booting" message in its iPXE configuration.

```console

$ curl -L http://192.168.200.1:9873/ipxe/de-ad-be-ef-00-00
#!ipxe

echo
echo ================================================================================
echo Warewulf v4 now booting: n1 (de:ad:be:ef:00:00)
echo
echo Container:     rockylinux-8

echo Kernel:        rockylinux-8 (container default)

echo KernelArgs:    quiet crashkernel=no vga=791 net.naming-scheme=v238
echo
[...]
```

If we edit n1 to have a different hwaddr:

```console
$ sudo wwctl node edit n1
Are you sure you want to modify 1 nodes: y

$ sudo wwctl node list -a n1 | grep hwaddr
  n1    default:hwaddr      --          de:ad:be:ef:de:ad                                     
```

We can no longer get the correct iPXE configuration either at the old address or the new address.

```console

$ curl -L http://192.168.200.1:9873/ipxe/de-ad-be-ef-00-00
#!ipxe

echo
echo ================================================================================
echo Warewulf v4
echo
echo MESSAGE: This node is unconfigured. Please have your system administrator add a
echo          configuration for this node with HW address: de:ad:be:ef:00:00
echo
echo Rebooting in 1 minute...
sleep 60
reboot
```

```console

$ curl -L http://192.168.200.1:9873/ipxe/de-ad-be-ef-de-ad
#!ipxe

echo
echo ================================================================================
echo Warewulf v4
echo
echo MESSAGE: This node is unconfigured. Please have your system administrator add a
echo          configuration for this node with HW address: de:ad:be:ef:de:ad
echo
echo Rebooting in 1 minute...
sleep 60
```
