### ISSUE TITLE
autopartitioning and local disk support

### ISSUE THREAD

**Issue by jcsiadal** [hpcng/warewulf#694]
Reference #403

Add support for automatic partitioning of local storage media and local copies of files from VNFS.

This is necessary for implementation of local scratch space; it can be done with custom scripts now, but we should support this directly in our node configuration. This would require additional node.conf options and another wwinit script.

This is step 1 in supporting diskfull installation.

Additionally, we should support excluding directories from the VNFS, which would be automatically rsync'ed to the local HD after local storage is partitioned.

**Comment by anderbubble** [comment]
Is this completed by https://github.com/hpcng/warewulf/pull/786?

**Comment by jcsiadal** [comment]
Mostly, but I'll close this and I'll create a different issue for part 2: configurable copy-on-boot from the VNFS remote chroot to the local drive.
