### ISSUE TITLE
consistent display of tag and nettag in wwctl node list -a

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#717]
### Version of Warewulf

What version of Warewulf are you using? Run

4.4

### Expected vs actual behavior

In `wwctl node list -a`, tags values are included as regular parameters; but nettag values are included with a tag: prefix. I suggest that they should be the same, either prepended with tag: or not in both cases.

### Steps to reproduce this behavior

```console
# wwctl node set --tagadd domain=example.com n1
# wwctl node set --nettagadd domain=example.net n1
# wwctl node list -a n1
```

### What OS/distro are you running

Rocky Linux 9

### How did you install Warewulf

built from source

**Comment by mslacken** [comment]
Fixed as the output is in devel:
```
 n01   NetDevs[default].Tags[domain]  --       example.net                                            
  n01   Tags[domain]                   --       example.com                
```
