### ISSUE TITLE
node list --long doesn't include everything from the default node list

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#736]
Considering

    # wwctl node list

vs

    # wwctl node list --long

Long shouldn't be missing info you can see without long. It's not a longer set of columns, it's a different set, which is non-intuitive. The right idea is probably to eliminate "--long" which is non-intuitive, and make a dstat-style set of options that adds groups of display columns to the output.

    # wwctl node list --net --profile --kernel --container --overlays --ipmi

This would be _very long_, but I asked for it. It would also require some re-thinking of the output for "--net".

From @elfurbe

**Comment by mslacken** [comment]
This bug is not valid any more. 
```wwctl node list --all```
will list *all* the set values, be it from a profile or the node itself.
Additionally we have now 
```wwctl node list --fullall```
will show *all* values including the fields with no value set at all.
