### ISSUE TITLE
wwlog should send output to stderr, not stdout

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#758]

**Comment by mslacken** [comment]
You mean stdout and stderr as info isn't an error.

**Comment by anderbubble** [comment]
I actually mean just stderr. I suggest that only the actual program output should go to stdout, and all logs should go to stderr. This is supported by the default behavior of the golang log package [1] as well as conversation at [2]. Also suggested by [3], though perhaps more vaguely.

Program output, then, should not be put through wwlog, but should be printed directly.

[1]: https://pkg.go.dev/log

[2]: https://www.reddit.com/r/golang/comments/jqvaft/why_does_the_log_package_always_output_to_stderr/

[3]: https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html

**Comment by anderbubble** [comment]
Before:

```console

[janderson@rocky warewulf]$ sudo wwctl node add asdf2 2>/dev/null
Added node: asdf2
```

After:

```console

[janderson@rocky warewulf]$ sudo wwctl node add asdf2 2>/dev/null
```

Looks good to me.
