### ISSUE TITLE
wwclient, no route to host

### ISSUE THREAD

**Issue by kivel** [hpcng/warewulf#77]
I lately run into the issue that the `wwclient` can't communicate with the master.
```
root@n4003:~# tail /var/log/wwclient.log 
[LOG]      2021/04/29 11:12:03 Updating live file system LIVE, cancel now if this is in error
[LOG]      2021/04/29 11:12:10 Get http://129.129.224.32:9873/overlay-runtime: dial tcp :987->129.129.224.32:9873: connect: no route to host
[LOG]      2021/04/29 11:12:12 Updating system
[LOG]      2021/04/29 11:12:12 ERROR: Failed running CPIO: exit status 2
```
I do have a route to the host. It can hardly be more specific of a route as this
```
root@n4003:~# ip route
default via 129.129.144.1 dev eno2 
default via 172.23.205.1 dev eth0 metric 30 onlink 
129.129.144.0/24 dev eno2 proto kernel scope link src 129.129.144.102 
129.129.224.32 via 172.23.205.1 dev eth0 
172.23.205.0/24 dev eth0 proto kernel scope link src 172.23.205.102 metric 30
```
I can also ping the master
``` 
root@n4003:~# ping 129.129.224.32
PING 129.129.224.32 (129.129.224.32) 56(84) bytes of data.
64 bytes from 129.129.224.32: icmp_seq=1 ttl=57 time=0.691 ms
```

is there an easy way to diagnose such issues?

**Comment by kivel** [comment]
OK, the qualifies partially as EBCAK. I forgot to copy the new `wwclient` to my system overlays.

Any suggestion how to prevent others from running into the same issue? Docu? additional command to put `wwclient` into the system overlays?

**Comment by gmkurtzer** [comment]
Hi Niko, 

Shouldn't the `make install` update wwclient in the system overlay? Granted, it won't rerun `wwctl overlay build -a`, is that the fix you are hoping to get documented?

Thank!

**Comment by kivel** [comment]
It will install it for the 'default', but not for any home brew overlays.
It's clearly my fault, as I missed to copy it into my sys-overlays. I think a hint in the doc is the least needed. So you can blame those that didn't RTFM

**Comment by gmkurtzer** [comment]
Haha, understood and sorry that was a PITA for ya. I'll leave this open until the documentation is updated.

Thanks again!

**Comment by kivel** [comment]
Sure, no rush on this.
There is one more thing to this, though.
Since the `wwclient` is in the system-overlay, the nodes will not know about changes on the master until they reboot. Since both need to match, the update of the master might render the runtime-overlay broken on the outdated nodes.
I have this situation right now. No big deal for me ... right now. But, we should keep this in mind that a `wwctl client upgrade`, or some other means might come handy later.

**Comment by gmkurtzer** [comment]
Hi @kivel,

I'm, rereading this, and kinda confused... The upgrade or reinstall should have dropped a new `wwclient` into the system overlay no matter how it was installed. Is the problem that `wwctl overlay build -s` wasn't invoked?

Thanks!

**Comment by kivel** [comment]
HI @gmkurtzer,
I haven't checked any of this lately, as I'm fully committed to other projects right now.
If I remember correctly, there is/was an incompatibility problem whenever the master upgrades and breaks with the client. In that case, the clients will be unable to talk to the master. So, there must be a procedure to upgrade the node, w/o rebooting them, to match master and client.

**Comment by mslacken** [comment]
Did not show up any more.
