### ISSUE TITLE
Wrong assignment of hwaddr with --discoverable=true

### ISSUE THREAD

**Issue by BeHom** [hpcng/warewulf#775]
### Version of Warewulf

```
wwctl version:   4.4.0-1.git_afcdb21
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.4.0-1.git_afcdb21"
```

### Expected behavior

using the "--discoverable=true" flag should add the received HW address to the default network interface.

### Actual behavior

The received HW address will be added to the eth0 interface which is in our case not the default network interface.

### Steps to reproduce this behavior

System setup with two network interfaces. The default interface belongs to eth1, the 2nd to eth0.
PXE boot configured via eth1 (dhcp config). 
Two network interfaces configured. 
```wwctl node add suse-node1 --netdev eth1 --ipaddr 192.168.1.11  --discoverable=true```
```wwctl node set suse-node1 --netname eth0 --ipaddr 10.25.114.55 --onboot=true --type=Ethernet```

Boot the server.
The system boots, but with the wrong hwaddr assignment. (/etc/warewulf/nodes.conf) causing network problems.
suse-node1:
    discoverable: "false"
    profiles:
    - default
    network devices:
      default:
        device: eth1
        ipaddr: 192.168.1.13
        primary: "true"
      eth0:
        type: Ethernet
        onboot: "true"
        ipaddr: 10.25.114.57
        hwaddr: 00:50:56:bc:36:9b

Changing the node configuration, e.g. copy the hwaddr under default network devices via 
"wwctl node edit suse-node1" will cause the problem that the node is unconfigured.
When I run the following command again 
```wwctl node set suse-node1 --netname eth0 --ipaddr 10.25.114.55 --onboot=true --type=Ethernet```
The system runs as expected. I think this is a problem you already know. 
 'wwctl node edit' inconsistent state with warewulfd #691 

### What OS/distro are you running

NAME="openSUSE Leap"
VERSION="15.4"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.4"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap

### How did you install Warewulf
Using rpm paket 
```zypper install https://github.com/hpcng/warewulf/releases/download/v4.4.0/warewulf-4.4.0-1.git_afcdb21.suse.lp153.x86_64.rpm```

**Comment by mslacken** [comment]
The actual behavior is that warewulf will assign the discovered mac address to the first network device of the node without a hw address. As the network devices are stored in a map, this can change from node to node, so sometimes its `eth0` other times it could be `eth1`. As work around you can assign (dummy) hw addresses to the network devices you do not want to be discovered.
But yes, the expected behavior is that the primary network device will get the hw address assigned. I will fix this.
