### ISSUE TITLE
document Ubuntu image creation

### ISSUE THREAD

**Issue by Moading** [hpcng/warewulf#783]
I'll post instructions for creating a working ubuntu image here in the next few days...

**Comment by anderbubble** [comment]
Thanks, @Moading. I'd like to get the image into https://github.com/hpcng/warewulf-node-images, in addition to adding a reference to them in the docs. I'll wait for your update.

**Comment by Moading** [comment]
This Containerfile

```
FROM ubuntu:latest

RUN echo $(uname -a)

#kernel and modules
RUN apt-get update
RUN apt-get -y install apt-utils
RUN apt-get -y install linux-image-5.19.0-38-generic
RUN apt-get -y install linux-modules-$(uname -r) linux-modules-extra-$(uname -r)

#remove netplan and install ifupdown
RUN apt-get -y install software-properties-common
RUN apt-get update
RUN apt-get -y remove netplan.io
RUN apt-get -y install ifupdown 

#nfs
RUN apt-get -y install nfs-common

#useful things
RUN apt-get -y install pciutils lshw rdma-core

#COPY excludes /etc/warewulf/
#COPY container_exit.sh /etc/warewulf/

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
```
contains the packages I installed to get my debootstrap image booting.

I executed `docker build . -t myubuntu_a -f Containerfile`

```
martin@server:~/ubuntu_container$ docker images
REPOSITORY                          TAG       IMAGE ID       CREATED        SIZE
myubuntu_a                          latest    f1c37197285e   14 hours ago   1.03GB
```
I do not know how to import it to warewulf now.

```
martin@server:~/ubuntu_container$ sudo wwctl container import 172.17.0.1://myubuntu_a:latest
Setting VNFS name: myubuntu_a:latest
ERROR  : invalid dir or uri: 172.17.0.1://myubuntu_a:latest
ERROR: invalid dir or uri: 172.17.0.1://myubuntu_a:latest
```
172.17.0.1 is the ip of the interface docker0, i geuess that is where dockerd is listening.

**Comment by mslacken** [comment]
Please use `ARG kernelversion=5.19.0-38-generic` instead of $(uname -r) as this will break your build on non ubuntu hosts.
I never used `docker` but always use `podman`, also there seems to be code in warewulf which can connect to a local docker daemon.
For podman the steps would be the following:
```
podman build -f ubuntu.docker -t ubuntu-ww4
podman image save localhost/ubuntu-ww4:latest  -o ubuntu.tar
wwctl container import file://root/ubuntu.tar ubuntu-jammy
```
You should also consider the ssh server inside the container so that you can connect to it.

**Comment by Moading** [comment]
Thanks @mslacken for your input. I have changed the container file and tested it - it works.
The following commands produce the warewulf container:

```
podman build -f Containerfile.txt -t ubuntu-a
podman image save localhost/ubuntu-a:latest -o ubuntu-a.tar
wwctl container import file://root/ubuntu-a.tar ubuntu-a
```

[Containerfile.txt](https://github.com/hpcng/warewulf/files/11289189/Containerfile.txt)

**Comment by anderbubble** [comment]
Ported to https://github.com/hpcng/warewulf-node-images/issues/26
