### ISSUE TITLE
support OCI registry login from wwctl

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#785]
Warewulf can already pull images from protected repositories after another OCI client (e.g., podman) has logged into it; but we should support direct login with `wwctl`.

In a perfect world I'd want `wwctl registry login` or `wwctl oci login`; or some such; but it seems wrong to create a whole subcommand category just for this one thing. So maybe `wwctl container login`?

**Comment by anderbubble** [comment]
@gmkurtzer how's this look to you? Any preferences on the CLI?

**Comment by anderbubble** [comment]
@JasonYangShadow any chance you already know how to do this?

**Comment by anderbubble** [comment]
I just discovered that Warewulf already supports this--at least, according to the docs at https://warewulf.org/docs/development/contents/containers.html#private-registry.

```
# export WAREWULF_OCI_USERNAME=privateuser
# export WAREWULF_OCI_PASSWORD=super-secret-password-or-token
# wwctl import docker://ghcr.io/privatereg/rocky:8
```

@gmkurtzer is this sufficient for the integration you'd have in mind?

**Comment by JasonYangShadow** [comment]
@anderbubble any conclusions for this feature?

**Comment by anderbubble** [comment]
I haven't tested it myself yet; but, if the `WAREWULF_OCI_USERNAME` and `WAREWULF_OCI_PASSWORD` variables work as documented, I think this should be sufficient.

**Comment by anderbubble** [comment]
Tested and confirmed this works.
