### ISSUE TITLE
Overlay import mode option doesn't do anything

### ISSUE THREAD

**Issue by jcsiadal** [hpcng/warewulf#791]
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.4.0-1.git_afcdb21"
Rocky Linux 8.7 -- OpenHPC 3.0 Factory RPM

```
wwctl overlay import generic --mode 777 /etc/munge/munge.key
ls -l /srv/warewulf/overlays/generic/etc/munge/
total 4
-r--------. 1 munge munge 1024 Apr 19 22:21 munge.key
```

This was just a test -- I wouldn't set a key to that, but "600" had the same result. As did "99999".
Not a high priority issue, as **wwctl overlay chmod** works fine. The mode option for mkdir also works.

**Comment by mslacken** [comment]
Closing this as the `--mode` flag isn't present any more
