### ISSUE TITLE
Adding new compute node slurm

### ISSUE THREAD

**Issue by edvinas31** [hpcng/warewulf#832]
### Version of Warewulf

What version of Warewulf are you using? Run

`wwctl version`

Hi, I was following the guide to install slurm https://www.admin-magazine.com/HPC/Articles/Warewulf-4-Time-and-Resource-Management , but I naturally got into the step where I wanted to add a new compute/slurm node to the cluster. This documentation did not quite make sense, because if following the guide administrator will have to add node entry in /etc/slurm/slurm.conf on frontend and also edit the same slurm.conf file in the image. This approach may result in human error mistypes. Is there a way to automate the process? For example if administrator adds a new compute node with wwctl then the same compute node is added in slurm.conf file both on frontend slurm conf and on compute node slurm conf files?

**Comment by anderbubble** [comment]
I advise against populating slurm.conf on compute nodes. In stead, use the "configless" support in slurmd to get the config from slurmctld.

https://slurm.schedmd.com/configless_slurm.html

Barring that, you can also use an `{{Include ""}}` directive in a cluster node overlay to bring slurm.conf from the head node into the compute node automaically. But using the configless support is much more straightforward.

**Comment by edvinas31** [comment]
Thank you for your input :)
