### ISSUE TITLE
ensure that Warewulf can be built without interference with /etc/warewulf/warewulf.conf

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#844]
https://hpcng.slack.com/archives/C019X4EUFFW/p1686004419569349

@griznog

**Comment by anderbubble** [comment]
I think this is fixed with all the recent changes to Makefile; but let me know if you're still having trouble, @griznog. (Sorry I failed to capture the actual notes here; these Slack links aren't usefully long-lived.)

**Comment by griznog** [comment]
Looks fixed to me.
