### ISSUE TITLE
simpler overlay names

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#852]
I suggest that Warewulf should build per-node overlays using static names like "system" or "wwinit" or "runtime" (within their existing per-node directories).

The current form of naming built overlays as a hypenated list of all the contained overlays doesn't scale well when many overlays are used simultaneously.

**Comment by griznog** [comment]
@mslacken is the one who knows for sure, but I think the long name one is just the merged version of all the individual overlays which is pulled during boot. The individual overlays  can be built individually with `wwctl overlay build -O overlayname` if they aren't there already.

It gets messy in WWPROVISION location if you add/remove overlays often, as those merged ones stack up, but that's just a part of the larger issue of `wwctl` not doing a lot of housekeeping anywhere for old versions of things. 

It'd be neat if it just built the individuals, then merged them on the fly when provisioning. I played around a bit with having them come in individually in the ipxe script, but that also doesn't scale well.

**Comment by anderbubble** [comment]
> I think the long name one is just the merged version of all the individual overlays which is pulled during boot.

Agreed. But this long name is what shows up in `wwctl status` for example, and it gets unwieldy.

**Comment by anderbubble** [comment]
See also #876.

**Comment by anderbubble** [comment]
Fixed in #883, though there's a bug. See #896
