### ISSUE TITLE
Hardcoded updateSystem loop interval

### ISSUE THREAD

**Issue by ArnaudDevelopper** [hpcng/warewulf#874]
Hello,
I took a look at root.go in the wwclient and I was wondering if there was any specific reason for hard coding the interval between calls to the updateSystem subroutine :
```go
		time.Sleep(1000 * time.Millisecond)
```
If not, I could try to do something a bit more generic i.e being able to change this interval dynamically through overlays.

**Comment by mslacken** [comment]
This isn't the update time, but the retry timer if `wwclient` couldn't connect to `warewuld`.
The update timer set in 
https://github.com/hpcng/warewulf/blob/546007423cff17d5bbdd966f7b392b6b0b20ab45/internal/app/wwclient/root.go#L134-L136
and can be configured in `warewulf.conf`
