### ISSUE TITLE
'File name too long' when building overlay for a node with a lot of overlays.

### ISSUE THREAD

**Issue by griznog** [hpcng/warewulf#876]
### Version of Warewulf

4.3.0-1.git_235c23

### Expected behavior

Overlays will be built.

### Actual behavior
```
DEBUG  : cpio: Cannot open /datapool/warewulf/provision/overlays/cpu-vm-1/autofs-backups-chrony-common-common-bhn-cron-dnsmasq-duo-fail2ban-firewalld-gdm-globus-gpu-httpd-libvirt-lustre-mlocate-motd-munge-namespaces-networking-nhc-nomachine-packages-pam-postfix-profile.d-root-rsyslog-samba-sbgrid-selinux-slurm-sshd-storage-setup-timezone-zfs-znapzend.img: File name too long
```
### Steps to reproduce this behavior

Add a lot of overlays to a node config.

### What OS/distro are you running

```sh
# cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
```

### How did you install Warewulf

Built from source.

@mslacken I found the limit of the current approach to naming the merged overlay for provisioning :D

**Comment by griznog** [comment]
That turned out to be pretty hard to find, but easy to fix. The actual name isn't important but using a fixed value for it seems to work so far in my testing environment. Will now go try this on my main cluster where overlays breed like rabbits and report if/how it works out there.

**Comment by anderbubble** [comment]
Thanks, @griznog. I thought I had already proposed this: I found #852, where I proposed just using the node's name as the built overlay name. What are you using in your testing?

**Comment by griznog** [comment]
You are correct that it does then use the same name for both, but I didn't catch that in my testing because 

1. I had included my system overlay in my runtime overlay list in some previous testing. 
2. The runtime overlay is built last, overwriting the system overlay which I didn't need because system overlay was also in the runtime overlay list. 

So this works great if you can ignore the distinction between system/runtime overlays, which I can do on my systems due to now using `wwclient` or the `wwinit` overlay.

**Comment by griznog** [comment]
Nope, won't work for me either. It also overwrites the indiviual overlay images, which I use later to pull specific overlays for updating. So back to the drawing board.

**Comment by griznog** [comment]
My lack of `git` skills aside, PR #882 fixes this mostly correctly?? Here's what the overlays look like after `wwctl overlay build -N cpu-vm-2` on my main cluster:

```
[I am root!@frankie:(bare)::overlays]# tree cpu-vm-2
cpu-vm-2
├── system-rocky8-x86_64.img
├── system-rocky8-x86_64.img.gz
├── __wwmerged_accccddffgglmmmnnnnpppprrssssssstzz.img
└── __wwmerged_accccddffgglmmmnnnnpppprrssssssstzz.img.gz
```

The node here has a single system overlay assigned and a long list of runtime overlays. There's still a limit with this approach of ~230 overlays but I think I'm ok with that as if I get to 230 overlays, it's probably time to re-think what I'm doing with overlays. 

I thought this would be better than a checksum because the name would still have some identifying characteristics, but now that I'm looking at it I don't think that theory holds. 

It might be better to have this function take another arg as a flag to select 'single', 'runtime' or 'system' and then return the correct name for a single overlay, runtime merged overlay or system merged overlay as needed. That would remove any doubt about what the name would be used for.

**Comment by griznog** [comment]
I guess there is one other idea, just abandon the distinction between system vs runtime overlays on the initial provisioning end and instead have `wwclient` use the node config to determine which overlays it updates post-boot based on some `wwclient` specific criteria, which could be the existing runtime/system naming or some other flag in the node/profile configs.
