### ISSUE TITLE
wwctl container file operation

### ISSUE THREAD

**Issue by mslacken** [hpcng/warewulf#88]
There is no proper way to copy files inside a existing container. It can be achieved by copy files directly to `/var/warewulf/container/chroots/FOO/rootfs`, so this is not pending issue.
Perhaps this could be possible by having a bind mount option `wwctl container exec --bind BAAR FOO /bin/bash`

**Comment by gmkurtzer** [comment]
Great idea. Do you want to take a stab at this, or shall I?

**Comment by gmkurtzer** [comment]
I'm playing with this now. Will report back shortly.

**Comment by gmkurtzer** [comment]
Done. Please test #97.

**Comment by gmkurtzer** [comment]
Do we want to escape the colon in the bind path?

**Comment by gmkurtzer** [comment]
This is done.
