### ISSUE TITLE
Can't build warewulf on a vanilla CentOS 7.9.2009

### ISSUE THREAD

**Issue by sandynomad** [hpcng/warewulf#89]
Following the Quickstart guide, warewulf fails to build.

    $ git clone https://github.com/hpcng/warewulf.git
    Cloning into 'warewulf'...
    remote: Enumerating objects: 5002, done.
    remote: Counting objects: 100% (1219/1219), done.
    remote: Compressing objects: 100% (823/823), done.
    remote: Total 5002 (delta 429), reused 1072 (delta 351), pack-reused 3783
    Receiving objects: 100% (5002/5002), 3.41 MiB | 3.23 MiB/s, done.
    Resolving deltas: 100% (2218/2218), done.
    $ cd warewulf
    $ make all
    golangci/golangci-lint info checking GitHub for tag 'v1.31.0'
    golangci/golangci-lint info found version: 1.31.0 for v1.31.0/linux/amd64
    golangci/golangci-lint info installed .tools/bin/golangci-lint
    get "google.golang.org/protobuf": found meta tag     get.metaImport{Prefix:"google.golang.org/protobuf", VCS:"git", RepoRoot:"https://go.googlesource.com/protobuf"} at //google.golang.org/protobuf?go-get=1
    go: github.com/containers/image/v5@v5.7.0 requires
    	github.com/containers/storage@v1.23.6 requires.
    	github.com/Microsoft/hcsshim@v0.8.9 requires
    	github.com/opencontainers/go-digest@v0.0.0-20180430190053-c9281466c8b2: invalid version: git fetch --unshallow -f origin in     /home/anon/go/pkg/mod/cache/vcs/552be1eeae05d101756f44ffae429e48bc88b11bff177e7eb912ebdd03383c62: exit status 128:
	fatal: git fetch-pack: expected shallow list
    make: *** [vendor] Error 1
    $ lsb_release -a
    LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
    Distributor ID:	CentOS
    Description:	CentOS Linux release 7.9.2009 (Core)
    Release:	7.9.2009
    Codename:	Core
    $

**Comment by sandynomad** [comment]
I was able to work around this issue by using "Red Hat Software Collections" and installing a later version of git.

(Add the Red Hat Software Collections Repo to the build OS)

    # yum -y install rh-git227-git-all
    ....
    $ scl enable rh-git227 httpd24 bash
    $ make all
    get "google.golang.org/protobuf": found meta tag get.metaImport{Prefix:"google.golang.org/protobuf", VCS:"git", RepoRoot:"https://go.googlesource.com/protobuf"} at //google.golang.org/protobuf?go-get=1
    go: downloading gopkg.in/yaml.v2 v2.4.0
    go: downloading github.com/opencontainers/image-spec v1.0.2-0.20190823105129-775207bd45b6
    go: downloading github.com/opencontainers/umoci v0.4.6
    go: downloading github.com/containers/image/v5 v5.7.0
    ....
    go: downloading github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
    get "golang.org/x/time": found meta tag get.metaImport{Prefix:"golang.org/x/time", VCS:"git", RepoRoot:"https://go.googlesource.com/time"} at //golang.org/x/time?go-get=1
    unused github.com/plus3it/gorecurcopy
    cd cmd/wwctl; go build -mod vendor -tags "containers_image_openpgp containers_image_ostree" -o ../../wwctl
    cd cmd/wwclient; CGO_ENABLED=0 GOOS=linux go build -mod vendor -a -ldflags '-extldflags -static' -o ../../wwclient
    $

I do not know enough about the "go" and "git" relationship to know whether they can be made to work together without updated RPMs from "Red Hat Software Collections".

**Comment by elguero** [comment]
I was able to confirm this issue and have submitted a PR.
