### ISSUE TITLE
[Bug]: "Offline Builds" are impossible

### ISSUE THREAD

**Issue by Kangie** [hpcng/warewulf#907]
### Version of Warewulf

commit f1eab8c363e135eca608c7471464e0fb5460bae7 (20230906)

4.4.1 does not generate configs in the same way, but does error during the `test` phase.

### Expected behavior

When all required dependencies are provided, builds should succeed, __especially__ in cases where the makefile supports an `OFFLINE_BUILD` variable!

I am attempting to package Warewulf for Gentoo Linux; all of our builds run in a sandboxed environment with no network access.

### Actual behavior

Currently builds fail when the `wwctl` binary is invoked during the build process (to generate configs) with a panic, here:

https://github.com/hpcng/warewulf/blob/f1eab8c363e135eca608c7471464e0fb5460bae7/internal/pkg/config/root.go#L112-L123

```
goroutine 1 [running]:
github.com/hpcng/warewulf/internal/pkg/config.(*RootConf).SetDynamicDefaults(0x555b2e273340)
        /var/tmp/portage/sys-cluster/warewulf-4.4.1_p20230907/work/warewulf-f1eab8c363e135eca608c7471464e0fb5460bae7/internal/pkg/config/root.go:123 +0xaf
github.com/hpcng/warewulf/internal/app/wwctl.rootPersistentPreRunE(0xc0002a9900?, {0xc000526be0?, 0x4?, 0x555b2d8c071b?})
        /var/tmp/portage/sys-cluster/warewulf-4.4.1_p20230907/work/warewulf-f1eab8c363e135eca608c7471464e0fb5460bae7/internal/app/wwctl/root.go:92 +0x125
github.com/spf13/cobra.(*Command).execute(0x555b2e210720, {0xc000526bc0, 0x2, 0x2})
        /var/tmp/portage/sys-cluster/warewulf-4.4.1_p20230907/work/warewulf-f1eab8c363e135eca608c7471464e0fb5460bae7/vendor/github.com/spf13/cobra/command.go:891 +0x75f
github.com/spf13/cobra.(*Command).ExecuteC(0x555b2e20b980)
        /var/tmp/portage/sys-cluster/warewulf-4.4.1_p20230907/work/warewulf-f1eab8c363e135eca608c7471464e0fb5460bae7/vendor/github.com/spf13/cobra/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0xc0000021a0?)
        /var/tmp/portage/sys-cluster/warewulf-4.4.1_p20230907/work/warewulf-f1eab8c363e135eca608c7471464e0fb5460bae7/vendor/github.com/spf13/cobra/command.go:968 +0x13
main.main()
        /var/tmp/portage/sys-cluster/warewulf-4.4.1_p20230907/work/warewulf-f1eab8c363e135eca608c7471464e0fb5460bae7/cmd/wwctl/main.go:13 +0x1e
make: *** [Makefile:52: etc/defaults.conf] Error 2
make: *** Waiting for unfinished jobs....
make: *** [Makefile:128: etc/bash_completion.d/wwctl] Error 2
make: *** [Makefile:145: man_pages] Error 2
```

#906 has been raised to correct this to a real error message, but the behaviour is still defective - it is impossible to successfully run `make all` in an offline environment:

```
./wwctl --emptyconf genconfig man docs/man/man1
./wwctl --emptyconf genconfig completions >etc/bash_completion.d/wwctl
ERROR: Couldn't establish a connection to remote: dial udp 8.8.8.8:80: connect: network is unreachable
make: *** [Makefile:145: man_pages] Error 255
```

### Steps to reproduce this behavior

This behaviour can be trivially reproduced using unshare:

```bash
kangie@monolith /data/development/temp/warewulf (development) $ make all
kangie@monolith /data/development/temp/warewulf (development) $ unshare -rn
monolith warewulf (development) # ./wwctl --emptyconf genconfig completions >etc/bash_completion.d/wwctl
ERROR: Couldn't determine IP address: dial udp 8.8.8.8:80: connect: network is unreachable
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.14"
```

### How did you install Warewulf

I'm attempting to write a Gentoo Linux package for inclusion in the main repository:

- https://github.com/Kangie/kangie-tools/blob/master/sys-cluster/warewulf/warewulf-4.4.1_p20230907.ebuild

**Comment by Kangie** [comment]
The more I think about it, the more this behaviour seems wrong: How is this supposed to work on a 'Dark Site'?

**Comment by mslacken** [comment]
Please check #853 which will add a private sub c address to config so that it works on a `dark side`. I wqil revert your PR #906 and merge #853 instead, but will add you to the contributors.

**Comment by Kangie** [comment]
Fantastic, I missed #853 but that patch resolves all of my issues.

I just wish I'd noticed it half a day ago, but now I know a dangerous amount of golang!

**Comment by mslacken** [comment]
Thanks again and keep as updated with your gentoo efforts.
You may want to add a  gentoo image to
https://github.com/hpcng/warewulf-node-images
so that others can use the images out of the box.
