### ISSUE TITLE
Add ipmihwaddr to node filelds/tags

### ISSUE THREAD

**Issue by seb45tian** [hpcng/warewulf#923]
I would like to suggest to add a tag `ipmihwaddr` to the node fields. Personally I would use it to modify the `dhcpd.conf.ww` template to assign static IPs to the BMC NICs. I know this could be achieved by just adding a custom tag - but in this case I think it would make sense, since this is an actual hardware nic with a mac address and I would expect it to have similar flags as other network interfaces.

**Comment by seb45tian** [comment]
Nevermind - I just realized there is also specifically an `ipmitagadd` option, which should suffice. Sorry for the noise.

**Comment by anderbubble** [comment]
No worries about noise; but for this kind of custom use case I do think that tags are a better fit. Thanks!
