### ISSUE TITLE
Warewulf nightly releases

### ISSUE THREAD

**Issue by anderbubble** [hpcng/warewulf#969]
### Summary

Create an automated nightly release of current Warewulf development.

### Rationale

This would make it easier for people to use and test the development build of Warewulf.

### Description

- Create a nightly release that describes its purpose.
- Create a GH automation that updates the artifacts associated with the nightly release.

### Additional information

I think that we should also, as part of this, change the existing release workflow to act based on the creation of a tag, rather than create a tag based on the creation of the release. That's more similar to what we're after here, and would simplify reusing the same or similar workflow for both use cases.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by anderbubble** [comment]
@elguero you were talking about potentially working on this; so tagging you here to coordinate the effort.

**Comment by aspfate** [comment]
I suggest to use docker approach instead current mock method.

**Comment by anderbubble** [comment]
@aspfate can you provide more information about what you mean, and what the benefit would be compared to building the RPM with Mock?

Mock provides an automated process that ensures that only packages identified as required for the build are included, which helps ensure that the spec is correct. Mock can also perform its work inside a container (though I don't know if that's how it's working here; I'd have to look further into it.)
